import {beforeAll,afterAll,describe,it,expect} from 'vitest'
import path from 'node:path'
import fs from 'node:fs/promises'
import {randomUUID,createHash} from 'node:crypto'
import {NativeClient} from '../packages/platform/native'
const testRoot=path.resolve('.test-data/native-'+randomUUID());let native:NativeClient
beforeAll(async()=>{await fs.mkdir(testRoot,{recursive:true});native=new NativeClient(path.resolve('native/bin/vm-fs.exe'))})
afterAll(()=>native.close())
describe('Windows 文件系统原生合同',()=>{
 it('无覆盖重命名，冲突时两个文件内容保持',async()=>{const source=path.join(testRoot,'source.txt'),destination=path.join(testRoot,'destination.txt');await fs.writeFile(source,'source');await fs.writeFile(destination,'destination');const info=await native.call('stat',{path:source});await expect(native.call('rename',{source,destination,identity:info.identity})).rejects.toThrow();expect(await fs.readFile(source,'utf8')).toBe('source');expect(await fs.readFile(destination,'utf8')).toBe('destination')})
 it('源身份不匹配时拒绝移动',async()=>{const source=path.join(testRoot,'identity.txt');await fs.writeFile(source,'safe');await expect(native.call('rename',{source,destination:path.join(testRoot,'bad.txt'),identity:'wrong'})).rejects.toThrow('SOURCE_CHANGED');expect(await fs.readFile(source,'utf8')).toBe('safe')})
 it('复制后独立校验，两阶段发布，持有源句柄到明确删除',async()=>{const source=path.join(testRoot,'copy-source.bin'),temporary=path.join(testRoot,'copy.tmp'),destination=path.join(testRoot,'copy-final.bin');const bytes=Buffer.alloc(256*1024,79);await fs.writeFile(source,bytes);const stat=await native.call('stat',{path:source});const token=randomUUID();const copy=await native.call('copy',{source,temporary,identity:stat.identity,token});expect(copy.hash).toBe(createHash('sha256').update(bytes).digest('hex'));await expect(fs.writeFile(source,'unexpected modification')).rejects.toThrow();expect(await fs.readFile(source)).toEqual(bytes);await native.call('publish',{temporary,destination,identity:copy.identity});expect(await fs.readFile(destination)).toEqual(bytes);expect(await fs.readFile(source)).toEqual(bytes);await native.call('removeHeld',{token,identity:stat.identity});await expect(fs.stat(source)).rejects.toThrow();expect(await fs.readFile(destination)).toEqual(bytes)})
 it('目标竞态冲突不覆盖已出现文件，也不删除源',async()=>{const source=path.join(testRoot,'race-source.txt'),temporary=path.join(testRoot,'race.tmp'),destination=path.join(testRoot,'race-final.txt');await fs.writeFile(source,'original');const stat=await native.call('stat',{path:source});const token=randomUUID();const copy=await native.call('copy',{source,temporary,identity:stat.identity,token});await fs.writeFile(destination,'racing file');await expect(native.call('publish',{temporary,destination,identity:copy.identity})).rejects.toThrow();await native.call('release',{token});expect(await fs.readFile(source,'utf8')).toBe('original');expect(await fs.readFile(destination,'utf8')).toBe('racing file')})
})
describe('FFmpeg 实际帧解码',()=>{
 for(const file of ['色彩与节奏.mp4','视频素材/变帧率 VFR.mp4','视频素材/WebM VP9.webm','BMP 样本.bmp'])it('解码 '+file,async()=>{const decoder=new NativeClient(path.resolve('native/bin/vm-media.exe'));try{const info=await decoder.call('open',{path:path.resolve('.test-data/fixtures',file)});expect(info.width).toBeGreaterThan(0);const frame=await decoder.call('frame',{time:file.endsWith('.bmp')?0:.8,step:0,output:path.join(testRoot,randomUUID()+'.png')});expect(frame.pts).toMatch(/^\d+$/);expect(frame.time).toBeLessThanOrEqual(.801);if(!file.endsWith('.bmp')){const next=await decoder.call('frame',{time:frame.time,step:1,output:path.join(testRoot,randomUUID()+'.png')});expect(next.time).toBeGreaterThan(frame.time);const previous=await decoder.call('frame',{time:next.time,step:-1,output:path.join(testRoot,randomUUID()+'.png')});expect(previous.pts).toBe(frame.pts)}}finally{decoder.close()}},20000)
 it('损坏视频返回错误，不留下无限等待',async()=>{const decoder=new NativeClient(path.resolve('native/bin/vm-media.exe'));try{await expect(decoder.call('open',{path:path.resolve('.test-data/fixtures/损坏的视频.mp4')})).rejects.toThrow()}finally{decoder.close()}})
})
