import { useEffect, useState } from 'react'
import { Wifi, ShieldCheck, Folder, ChevronDown, ChevronRight, Copy, RefreshCw, Monitor, Smartphone, Link, Play, Square, LoaderCircle } from 'lucide-react'
import type { Bootstrap } from '../../../../packages/contracts'
import type { ShareOptions, ShareStatus } from '../../../../packages/contracts/sharing'
import './SharingSettings.css'

function SharedFolder({id,name,selected,setSelected,disabled,depth=0}:{id:string;name:string;selected:string[];setSelected:(value:string[])=>void;disabled:boolean;depth?:number}){
 const [open,setOpen]=useState(false),[children,setChildren]=useState<{id:string;name:string}[]|null>(null),[error,setError]=useState('')
 const expand=async()=>{if(open){setOpen(false);return}setOpen(true);if(children)return;try{setChildren(await window.vm.shareFolders(id))}catch(e){setError(String(e));setChildren([])}}
 return <div className="share-folder"><div className="share-folder-row"><button className="share-expand" type="button" aria-label={(open?'收起 ':'展开 ')+name} aria-expanded={open} onClick={()=>void expand()}>{open?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button><label><input type="checkbox" checked={selected.includes(id)} aria-label={'共享 '+name} disabled={disabled||!selected.includes(id)&&selected.length>=64} onChange={e=>setSelected(e.target.checked?[...selected,id]:selected.filter(value=>value!==id))}/><Folder size={17}/><span title={name}>{name}</span></label></div>{open&&<div className="share-folder-children">{children===null?<small><LoaderCircle size={13}/>正在读取子目录…</small>:children.length&&depth<32?children.map(child=><SharedFolder key={child.id} {...child} selected={selected} setSelected={setSelected} disabled={disabled} depth={depth+1}/>):<small>{error||'没有更多子目录'}</small>}</div>}</div>
}
export function SharingSettings({data,notify}:{data:Bootstrap;notify:(message:string)=>void}){
 const remembered=data.settings.lanSharing as Partial<ShareOptions>|undefined
 const [status,setStatus]=useState<ShareStatus|null>(null),[host,setHost]=useState(remembered?.host??''),[port,setPort]=useState(remembered?.port??8899),[selected,setSelected]=useState<string[]>(remembered?.folderIds??[]),[maxDevices,setMaxDevices]=useState(remembered?.maxDevices??6),[keepInTray,setKeepInTray]=useState(remembered?.keepInTray??true),[busy,setBusy]=useState(''),[error,setError]=useState('')
 useEffect(()=>{let alive=true;let pending=false;let initial=true;const update=async()=>{if(pending)return;pending=true;try{const value=await window.vm.shareStatus();if(!alive)return;setStatus(value);if(initial){initial=false;const options=value.options;if(options){setHost(options.host);setPort(options.port);setSelected(options.folderIds);setMaxDevices(options.maxDevices);setKeepInTray(options.keepInTray)}else if(!value.interfaces.some(item=>item.address===host))setHost(value.interfaces[0]?.address??'127.0.0.1')}}catch(e){if(alive)setError(String(e))}finally{pending=false}};void update();const timer=setInterval(()=>void update(),5000);const off=window.vm.onEvent(e=>{if(e.topic==='sharing-changed')void update()});return()=>{alive=false;clearInterval(timer);off()}},[])
 const run=async(label:string,fn:()=>Promise<ShareStatus>)=>{setBusy(label);setError('');try{setStatus(await fn())}catch(e){setError(String(e))}finally{setBusy('')}}
 const running=!!status?.running,disabled=running||!!busy,expired=!!status&&status.qrExpires<=Date.now()
 return <div className="sharing-settings"><div className="share-heading"><span className="share-heading-icon"><Wifi size={24}/></span><div><h3>局域网共享</h3><p className="muted">把选定的媒体目录，带到手机与其他设备上。</p></div><span className={'share-status '+(running?'active':'')}><span/>{running?'共享已开启':'共享已关闭'}</span></div>
 <div className="share-principles"><span><ShieldCheck size={16}/>仅浏览与播放</span><span><Folder size={16}/>按目录授权</span><span><Smartphone size={16}/>浏览器直接访问</span></div>
 {(error||status?.error)&&<p className="inline-error" role="alert">{error||status?.error}</p>}
 {!status&&<p className="muted" role="status">正在读取共享状态…</p>}
 {running&&status&&<><div className="share-access"><div className={'share-qr '+(expired?'expired':'')}><img src={status.qr} alt="局域网共享连接二维码"/><small>{expired?'二维码已过期':'手机扫码，自动连接'}</small></div><div className="share-access-info"><span className="share-kicker">连接你的设备</span><strong className="share-connection-title">扫码即可浏览与播放</strong><p className="share-connection-note">无需输入配对码。二维码包含访问授权，请只向可信设备展示。</p><strong className="share-address"><Link size={16}/>{status.url}</strong><span className={'share-qr-expiry '+(expired?'expired':'')}>{expired?'请刷新二维码后重新扫描':`二维码有效至 ${new Date(status.qrExpires).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`}</span><div className="share-access-actions"><button className="text-button" disabled={!!busy} onClick={()=>void run('正在刷新二维码',()=>window.vm.shareRenewQr())}><RefreshCw size={14}/>刷新二维码</button><button className="text-button" disabled={expired||!!busy} onClick={()=>void window.vm.shareCopyConnection().then(()=>notify('连接链接已复制，包含访问授权')).catch(e=>setError(String(e)))}><Copy size={14}/>复制连接链接</button></div><small>刷新使旧二维码失效，已连接设备继续使用。普通网址不包含访问权限。</small></div></div>
 <h4 className="share-devices-heading">已授权设备 <span className="badge">{status.devices.length} / {maxDevices}</span></h4><div className="share-devices">{!status.devices.length?<p className="muted">等待设备扫码连接，连接后会显示在这里。</p>:status.devices.map(device=><div className="share-device" key={device.id}><Monitor size={21}/><div><strong>{device.name}</strong><small>{device.address} · 最近访问 {new Date(device.lastSeen).toLocaleTimeString('zh-CN')}</small><span>{device.playing?'正在观看 · '+device.playing:device.streams?'正在读取媒体':'已授权'}</span></div><button className="text-button" disabled={!!busy} onClick={()=>void run('正在撤销设备并刷新二维码',()=>window.vm.shareRevoke(device.id))}>撤销授权</button></div>)}</div></>}
 <details className="share-config" open={!running}><summary>共享配置</summary> <div className="share-config-grid"><label className="field">共享网络<select aria-label="共享网络" disabled={disabled} value={host} onChange={e=>setHost(e.target.value)}>{status?.interfaces.map(item=><option key={item.address} value={item.address}>{item.loopback?'仅本机预览':item.name} · {item.address}</option>)}</select></label><label className="field">监听端口<input aria-label="共享端口" type="number" min="1024" max="65535" value={port} disabled={disabled} onChange={e=>setPort(Number(e.target.value))}/></label></div>
 <div className="share-folder-heading"><strong>共享目录</strong><small>已选择 {selected.length} / 64</small></div><p className="muted share-small">勾选目录即包含其所有子目录；展开后可只选择其中一部分。</p><div className="share-folder-picker">{data.roots.length?data.roots.map(root=><SharedFolder key={root.entryId} id={root.entryId} name={root.name} selected={selected} setSelected={setSelected} disabled={disabled}/>):<p className="muted">请先添加资源目录并完成索引。</p>}</div>
 <div className="setting-row"><div><strong>设备数量上限</strong><small>授权有效期 24 小时；默认最多 6 台设备。</small></div><select aria-label="共享设备数量上限" disabled={disabled} value={maxDevices} onChange={e=>setMaxDevices(Number(e.target.value))}>{[1,2,4,6,8,12,16].map(value=><option key={value} value={value}>{value} 台设备</option>)}</select></div>
 <div className="setting-row"><div><strong>关闭窗口后继续共享</strong><small>开启时关闭窗口会隐藏到托盘；从托盘菜单可停止共享并退出。</small></div><input type="checkbox" aria-label="关闭窗口后继续共享" checked={keepInTray} disabled={disabled} onChange={e=>setKeepInTray(e.target.checked)}/></div>
 </details>
 <div className="share-start-row"><p className="muted share-small">共享默认关闭，重启后需手动开启。电脑休眠或退出程序会中断播放。</p>{running?<button className="secondary" disabled={!!busy} onClick={()=>void run('正在停止',()=>window.vm.shareStop())}><Square size={15}/>停止共享</button>:<button className="primary" disabled={!!busy||!status||!host||!selected.length||!Number.isInteger(port)||port<1024||port>65535} onClick={()=>void run('正在开启',()=>window.vm.shareStart({host,port,folderIds:selected,maxDevices,keepInTray}))}><Play size={16}/>开启共享</button>}</div>
 {busy&&<p className="share-busy" role="status"><LoaderCircle size={14} className="spin"/>{busy}…</p>}

 <details className="share-help"><summary>连接与播放说明</summary><p>设备与电脑需位于可互访的局域网。连接失败时检查所选网卡、Wi-Fi 访客隔离和 Windows 防火墙；如系统弹出网络访问提示，只允许可信的专用网络。</p><p>二维码和复制的连接链接都包含授权信息，有效期 10 分钟；连接后授权有效期 24 小时。撤销设备会中断其访问并自动更新二维码，其他已连接设备继续使用。</p><p>本版本使用 HTTP，在可信局域网内开启。视频使用原文件直接播放，浏览器支持范围决定格式兼容性；暂不提供转码、外置字幕或公网访问配置。</p><p>关闭共享、切换媒体库、移除或重绑资源根目录会撤销设备会话。播放进度保存在访问设备的浏览器中，不覆盖桌面端进度。</p></details></div>
}
