import {applyTheme,themePresets,isThemePreset} from './palette'
import React,{useCallback,useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query'
import * as Popover from '@radix-ui/react-popover'
import {Library,Folder,FolderOpen,FolderPlus,Image as ImageIcon,Film,Star,Tag,Tags,Users,Search,LayoutGrid,List,ChevronDown,ChevronRight,ArrowLeft,ArrowRight,ArrowUp,SlidersHorizontal,Settings2,Activity,HardDrive,RefreshCw,X,Check,Plus,MapPin,ImagePlus,Trash2,FolderInput,Info,LoaderCircle,MonitorPlay,PanelLeftClose,PanelLeftOpen,MoreHorizontal,Clapperboard,Palette,Moon,Sun,Monitor} from 'lucide-react'
import type {Bootstrap,Entry,Page,Plan,QuerySession,Root,Selection,Task} from '../../../../packages/contracts'
import {defaultCoverQuality,type CoverQuality} from '../../../../packages/contracts/covers'
import {defaultQuery,selection,useNavigation,persistentBrowse} from './store'
import {Busy,EntryMenu,IconButton,Modal,Thumb,ViewBoundary,clearThumbCache,formatSize,formatTime,type EntryAction} from './components'
import {Viewport} from './Viewport'
import {FilterPopover} from './FilterPopover'
import {Viewer} from './Viewer'
import {CoverEditor} from './CoverEditor'
import {ScrapeModal} from './ScrapeModal'
import {Settings,Tasks} from './Settings'
import {ActressView} from './ActressView'
import {MoviesView} from './MoviesView'
import './styles.css'
import './aceternity.css'
import {AuroraBackdrop,AuroraScope,Sparkles,TextReveal} from './aceternity/effects'

const client=new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:false,gcTime:60000}}})
/* 标题栏主题快捷切换：一键换主题预设与明暗模式，完整自定义仍在设置页。 */
function ThemeQuickSwitch({data}:{data:Bootstrap}){
 const [open,setOpen]=useState(false)
 const isCustom=typeof data.settings.accentColor==='string'&&/^#[0-9a-f]{6}$/i.test(data.settings.accentColor)
 const currentPreset=!isCustom&&isThemePreset(data.settings.themePreset)?data.settings.themePreset:'aurora'
 const theme=String(data.settings.theme??'system')
 const save=(patch:Record<string,unknown>)=>void window.vm.settings(patch).catch(()=>{})
 return <Popover.Root open={open} onOpenChange={setOpen}>
  <Popover.Trigger asChild><button className="icon-button theme-quick" aria-label="快捷切换主题" title="快捷切换主题"><Palette size={15}/></button></Popover.Trigger>
  <Popover.Portal><Popover.Content className="theme-quick-popover" sideOffset={10} align="end" aria-label="界面主题">
   <strong>界面主题</strong><small>双色渐变随主题即时切换</small>
   <div className="theme-quick-grid">{themePresets.map(item=><button key={item.id} className={'theme-quick-swatch'+(!isCustom&&currentPreset===item.id?' selected':'')} title={item.name+'主题'} aria-label={item.name+'主题'} onClick={()=>save({themePreset:item.id,accentColor:null})}><span style={{background:`linear-gradient(135deg, ${item.accent}, ${item.accent2})`}}/><small>{item.name}</small></button>)}</div>
   <div className="theme-quick-row">{([['system','自动',Monitor],['dark','深色',Moon],['light','浅色',Sun]] as const).map(([id,label,Icon])=><button key={id} className={theme===id?'selected':''} onClick={()=>save({theme:id})}><Icon size={13}/>{label}</button>)}</div>
  </Popover.Content></Popover.Portal>
 </Popover.Root>
}
function App(){
 const bootstrap=useQuery({queryKey:['bootstrap'],queryFn:()=>window.vm.bootstrap()});const data=bootstrap.data
 const query=useNavigation(s=>s.query);const view=useNavigation(s=>s.view);const selected=useNavigation(s=>s.selected);const snapshot=useNavigation(s=>s.snapshot);const snapshotCount=useNavigation(s=>s.snapshotCount);const navigate=useNavigation(s=>s.navigate);const setQuery=useNavigation(s=>s.setQuery);const select=useNavigation(s=>s.select);const history=useNavigation(s=>s.history);const future=useNavigation(s=>s.future)
 const [epoch,setEpoch]=useState(0);const [search,setSearch]=useState('');const [pendingUpdates,setPendingUpdates]=useState(false);const [toast,setToast]=useState('');const [taskMap,setTaskMap]=useState<Map<string,Task>>(new Map());const [showSettings,setShowSettings]=useState(false);const [showTasks,setShowTasks]=useState(false);const [showTags,setShowTags]=useState(false);const [collapsed,setCollapsed]=useState(false)
 const [add,setAdd]=useState<Awaited<ReturnType<typeof window.vm.pickRoot>>>(null);const [adding,setAdding]=useState(false);const [preview,setPreview]=useState<Entry|null>(null);const [viewer,setViewer]=useState<{entry:Entry;session:QuerySession;index:number}|null>(null);const [cover,setCover]=useState<{entry:Entry;time:number}|null>(null);const [organize,setOrganize]=useState<{selection:Selection;entry:Entry|null}|null>(null);const [operation,setOperation]=useState<{kind:'rename'|'move'|'trash';selection:Selection;entry:Entry|null}|null>(null);const [scrape,setScrape]=useState<Entry|null>(null)
 const initialized=useRef(false);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const overlays=useRef(false);overlays.current=!!(showSettings||showTasks||showTags||add||preview||viewer||cover||organize||operation||scrape)
 const notify=useCallback((message:string)=>{setToast(message.replace(/^Error: Error invoking remote method '[^']+': Error: /,''));if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),6000)},[])
 const refresh=useCallback(()=>{void client.invalidateQueries({queryKey:['bootstrap']});setEpoch(e=>e+1);setPendingUpdates(false)},[])
 const replaceEntry=useCallback((entry:Entry)=>{client.setQueriesData<Page>({queryKey:['page']},page=>page?{...page,entries:page.entries.map(item=>item.id===entry.id?entry:item)}:page);client.setQueriesData<Entry[]>({queryKey:['tree']},items=>items?.map(item=>item.id===entry.id?entry:item));client.setQueriesData<Entry[]>({queryKey:['path-children']},items=>items?.map(item=>item.id===entry.id?entry:item))},[])
 const sessionQuery=useQuery({queryKey:['browse',query,epoch],queryFn:async()=>{const next=await window.vm.openQuery(query);const first=await window.vm.page(next.id,0,100);client.setQueryData(['page',next.id,0],first);return next},enabled:!!data,staleTime:0,gcTime:0,placeholderData:previous=>previous})
 const session=sessionQuery.data
 const ancestors=useQuery({queryKey:['ancestors',query.folderId,epoch],queryFn:()=>window.vm.ancestors(query.folderId!),enabled:!!query.folderId,staleTime:Infinity,placeholderData:previous=>previous})
 const current=ancestors.data?.at(-1)
 useEffect(()=>{if(data&&!initialized.current){initialized.current=true;setTaskMap(new Map(data.tasks.map(t=>[t.id,t])));if(data.settings.lastBrowse){useNavigation.getState().hydrate(data.settings.views,data.settings.lastBrowse)}else if(typeof data.settings.lastFolder==='string'&&data.roots.length){void window.vm.entry(data.settings.lastFolder).then(e=>navigate(e.id,'direct')).catch(()=>{})}}},[data])
 useEffect(()=>{if(!data)return;const theme=String(data.settings.theme??'system'),system=window.matchMedia('(prefers-color-scheme: dark)');document.documentElement.dataset.theme=theme;const update=()=>applyTheme(data.settings.themePreset,data.settings.accentColor,theme==='dark'||theme==='system'&&system.matches);update();system.addEventListener('change',update);return()=>system.removeEventListener('change',update)},[data?.settings.theme,data?.settings.themePreset,data?.settings.accentColor])
 useEffect(()=>{const timeout=setTimeout(()=>{if(query.text!==search)setQuery({text:search})},180);return()=>clearTimeout(timeout)},[search])
 useEffect(()=>setSearch(query.text),[query.text])
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>|null=null;const unsubscribe=useNavigation.subscribe(state=>{if(!initialized.current)return;if(timer)clearTimeout(timer);timer=setTimeout(()=>{const current=persistentBrowse(state);const views={...state.views,[state.query.folderId??'library']:current};void window.vm.settings({lastBrowse:current,views:Object.fromEntries(Object.entries(views).slice(-50))}).catch(()=>{})},600)});return()=>{unsubscribe();if(timer)clearTimeout(timer)}},[])
 useEffect(()=>window.vm.onEvent(event=>{if(event.topic==='task'){const task=event.data as Task;setTaskMap(map=>new Map(map).set(task.id,task))}if(event.topic==='entry-changed')replaceEntry(event.data as Entry);if(event.topic==='thumbnail-cache-cleared')clearThumbCache();if(event.topic==='settings-changed')void client.invalidateQueries({queryKey:['bootstrap']});if(event.topic==='changed'){void client.invalidateQueries({queryKey:['bootstrap']});const state=useNavigation.getState();if(state.selected.length||state.snapshot||overlays.current)setPendingUpdates(true);else setEpoch(e=>e+1)}if(event.topic==='library-switched'){initialized.current=false;clearThumbCache();useNavigation.getState().reset();setSearch('');setTaskMap(new Map());client.clear();setEpoch(e=>e+1)}}),[replaceEntry])
 const count=snapshot?snapshotCount:selected.length;const allTasks=[...taskMap.values()];const activeTasks=allTasks.filter(t=>['running','paused'].includes(t.state));const layout=data?.plugins.find(p=>p.slot==='content.layout'&&p.enabled)?.id.endsWith('content-list')?'list':'grid';const navigation=data?.plugins.find(p=>p.slot==='navigation.presenter'&&p.enabled)?.id.endsWith('navigation-visual')?'visual':'tree';const imageEnabled=data?.plugins.some(p=>p.id==='builtin.viewer-image'&&p.enabled);const videoPlugin=data?.plugins.find(p=>p.slot==='viewer.video'&&p.enabled);const videoEnabled=!!videoPlugin;const videoPlayer=videoPlugin?.id==='builtin.viewer-mpv'?'mpv':videoPlugin?.id==='builtin.viewer-system'?'system':'chromium'
 const open=useCallback((entry:Entry,index:number)=>{if(entry.kind==='folder')navigate(entry.id,'direct');else if((entry.kind==='image'&&!imageEnabled)||(entry.kind==='video'&&!videoEnabled))notify('此查看器插件已停用，请在设置中启用或使用系统默认应用打开');else if(entry.kind==='video'&&videoPlayer==='system')void window.vm.system(entry.id,'open').catch(e=>notify(String(e)));else if(session)setViewer({entry,index,session})},[navigate,session,imageEnabled,videoEnabled,videoPlayer,notify])
 // 电影卡片点击：保持电影页不变，按当前电影排序构建会话并弹出播放窗口（与资源目录视频卡片一致）。
 const openMovie=useCallback((entry:Entry,movieSession:QuerySession,index:number)=>{
  if(!videoEnabled){notify('此查看器插件已停用，请在设置中启用或使用系统默认应用打开');return}
  if(videoPlayer==='system'){void window.vm.system(entry.id,'open').catch(e=>notify(String(e)));return}
  setViewer({entry,index,session:movieSession})
 },[videoEnabled,videoPlayer,notify])
 const locate=(entry:Entry)=>{if(entry.parentId){navigate(entry.parentId,'direct',{...defaultQuery,folderId:entry.parentId,scope:'direct'});select([entry.id]);setPreview(null);setViewer(null)}}
 const action=useCallback((action:EntryAction,entry:Entry,index?:number)=>{const state=useNavigation.getState();const chosen=state.selected.includes(entry.id)||state.snapshot?selection():{ids:[entry.id]};
  if(action==='open'){if(index!==undefined)open(entry,index);else if(entry.kind==='folder')navigate(entry.id);return}
  if(action==='preview'){if(entry.kind==='folder')setPreview(entry);else if(index!==undefined)open(entry,index);else{void window.vm.openQuery({...defaultQuery,folderId:entry.parentId,scope:'direct'}).then(async q=>{for(let offset=q.folders;offset<q.total;offset+=200){const p=await window.vm.page(q.id,offset,200);const i=p.entries.findIndex(e=>e.id===entry.id);if(i>=0){setViewer({entry,session:q,index:offset+i});break}}}).catch(e=>notify(String(e)))}return}
  if(action==='favorite'){void window.vm.organize(chosen,'favorite',!entry.favorite).then(()=>{refresh();notify(entry.favorite?'已取消收藏':'已添加收藏')}).catch(e=>notify(String(e)));return}
  if(action==='tags'){setOrganize({selection:chosen,entry});return}if(action==='cover'){setCover({entry,time:0});return}if(action==='scrape'){setScrape(entry);return}if(action==='locate'){locate(entry);return}
  if(['rename','move','trash'].includes(action)){setOperation({kind:action as 'rename'|'move'|'trash',selection:chosen,entry});return}
  void window.vm.system(entry.id,action==='external'?'open':action as 'copy'|'reveal').then(()=>{if(action==='copy')notify('路径已复制')}).catch(e=>notify(String(e)))
 },[open,navigate,notify,refresh])
 const addRoot=async()=>{try{const root=await window.vm.pickRoot();if(root)setAdd(root)}catch(e){notify(String(e))}}
 const switchLayout=async(mode:string)=>{const plugin=data?.plugins.find(p=>p.id==='builtin.content-'+mode);if(plugin)try{await window.vm.setPlugin(plugin.id,true,plugin.config);void client.invalidateQueries({queryKey:['bootstrap']})}catch(e){notify(String(e))}}
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='f'){event.preventDefault();document.querySelector<HTMLInputElement>('.search-box input')?.focus();return}if((event.target as HTMLElement).matches('input,textarea,select,[contenteditable]')||overlays.current)return;const state=useNavigation.getState();if(event.altKey&&event.key==='ArrowLeft'){event.preventDefault();state.back()}if(event.altKey&&event.key==='ArrowRight'){event.preventDefault();state.forward()}if(event.altKey&&event.key==='ArrowUp'&&current?.parentId){event.preventDefault();navigate(current.parentId)}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'&&session){event.preventDefault();void window.vm.freeze(session.id).then(s=>select([],s.snapshotId,s.count)).catch(e=>notify(String(e)))}if(event.key==='Escape')select([]);if(event.key==='F5'){event.preventDefault();refresh()}if(event.key==='Delete'&&(state.selected.length||state.snapshot)){event.preventDefault();setOperation({kind:'trash',selection:selection(),entry:null})}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[session,current,navigate,notify,refresh])
 if(bootstrap.isError)return <div className="startup-error"><h1>无法打开媒体库</h1><p>{String(bootstrap.error)}</p><button className="primary" onClick={()=>void bootstrap.refetch()}>重试</button></div>
 if(!data)return <div className="startup"><div className="startup-inner"><Sparkles count={34}/><div className="brand-mark">V</div><Busy label="正在打开本地媒体库…"/></div></div>
 return <div className={'app '+(collapsed?'sidebar-collapsed':'')}>
  <AuroraBackdrop/>
  <div className="titlebar"><div className="title-brand"><span className="brand-mini">V</span><strong>VideoManager</strong><span>本地媒体工作台</span></div><ThemeQuickSwitch data={data}/><span className="title-private"><span/>离线优先 · 媒体保留原位</span></div>
  <aside className="sidebar"><div className="library-label"><span>媒体库</span><span className="badge">LOCAL</span></div><button className={'nav-button '+(view==='library'&&!query.folderId&&!query.favorite&&!query.tags.length&&!query.actress?'selected':'')} onClick={()=>navigate(null,'library',{...defaultQuery})}><Library size={19}/><span>全部媒体</span></button><button className={'nav-button '+(view==='library'&&query.favorite?'selected':'')} onClick={()=>navigate(null,'library',{...defaultQuery,favorite:true})}><Star size={19}/><span>我的收藏</span></button><button className={'nav-button '+(view==='movies'?'selected':'')} onClick={()=>useNavigation.getState().openMovies()}><Clapperboard size={19}/><span>电影</span>{!!data.movieCount&&<span className="count-badge">{data.movieCount>999?'999+':data.movieCount}</span>}</button><button className={'nav-button '+(view==='actresses'?'selected':'')} onClick={()=>useNavigation.getState().openActresses()}><Users size={19}/><span>女优</span>{!!data.actressCount&&<span className="count-badge">{data.actressCount>999?'999+':data.actressCount}</span>}</button>
   <div className="sidebar-tags">{data.tags.length?<button className={'nav-button'+(query.tags.length?' selected':'')} onClick={()=>setShowTags(true)}><Tags size={19}/><span>标签</span><span className="count-badge">{data.tags.length>999?'999+':data.tags.length}</span></button>:<button className="nav-button" onClick={()=>setShowTags(true)}><Tags size={19}/><span>标签</span></button>}</div>
   <div className="sidebar-heading"><span>资源目录</span></div><div className="root-tree">{data.roots.map(root=><RootNode key={root.id} root={root} current={query.folderId} ancestors={ancestors.data??[]} mode={navigation} epoch={epoch} onNavigate={id=>navigate(id)}/>) }{!data.roots.length&&<p className="sidebar-empty">添加本地文件夹<br/>开始构建你的媒体库</p>}</div><button className="add-source" onClick={()=>void addRoot()}><FolderPlus size={17}/><span>添加资源目录</span></button>
   <div className="sidebar-bottom"><button className="nav-button" onClick={()=>setShowTasks(true)}><Activity size={18}/><span>后台任务</span>{activeTasks.length>0&&<span className="count-badge">{activeTasks.length}</span>}</button><button className="nav-button" onClick={()=>setShowSettings(true)}><Settings2 size={18}/><span>设置与插件</span></button><div className="local-status"><span className="status-dot online"/>所有数据仅保存在本机</div></div>
  </aside>
  <main className="main"><div className="pathbar"><div className="navigation-buttons"><IconButton label={collapsed?'展开侧栏':'收起侧栏'} onClick={()=>setCollapsed(v=>!v)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</IconButton><IconButton label="后退 (Alt+←)" disabled={!history.length} onClick={()=>useNavigation.getState().back()}><ArrowLeft size={19}/></IconButton><IconButton label="前进 (Alt+→)" disabled={!future.length} onClick={()=>useNavigation.getState().forward()}><ArrowRight size={19}/></IconButton><IconButton label="上一级 (Alt+↑)" disabled={!current?.parentId} onClick={()=>{if(current?.parentId)navigate(current.parentId)}}><ArrowUp size={18}/></IconButton></div><div className="breadcrumb"><button onClick={()=>navigate(null,'library',{...defaultQuery})}><Library size={16}/></button>{query.folderId&&view==='library'&&ancestors.data?ancestors.data.map((entry,i)=><React.Fragment key={entry.id}><ChevronRight size={13}/><PathCrumb entry={entry} current={i===ancestors.data!.length-1} onNavigate={id=>navigate(id)}/></React.Fragment>):<strong>{view==='movies'?'电影':view==='actresses'?'女优':query.favorite?'我的收藏':query.actress?'女优 · '+query.actress:query.tags.length?'标签 · '+query.tags.join('、'):'全部媒体'}</strong>}</div>{view==='library'&&<div className="search-box"><Search size={17}/><input aria-label="在所选路径下搜索文件名、文件夹名或标签" placeholder={query.folderId?'搜索所选路径下的媒体、文件夹或标签…':'搜索全部媒体、文件夹或标签…'} value={search} onChange={e=>setSearch(e.target.value)}/><SearchFieldPicker/>{search&&<button className="icon-button" aria-label="清空搜索" onClick={()=>setSearch('')}><X size={14}/></button>}<span>Ctrl F</span></div>}</div>
   <div className="page-heading"><div><div className="eyebrow">{view==='actresses'?'ACTRESS COLLECTION':view==='movies'?'MOVIE COLLECTION':query.scope==='library'?'YOUR LOCAL COLLECTION':'EXPLORE YOUR LIBRARY'}</div><h1>{view==='movies'?'电影':view==='actresses'?'女优':query.folderId?current?.name??'正在打开…':query.favorite?'我的收藏':query.actress?query.actress:query.tags.length?query.tags.join(' · '):'全部媒体'}<span className="heading-dot"/></h1><p>{view==='movies'?'资源库中已刮削的全部影片，点击卡片在当前页面弹出播放窗口。':view==='actresses'?'由视频刮削结果自动汇总，点击卡片查看该女优的全部作品。':data.roots.length?query.folderId?(current?.rootState==='offline'?'资源目录离线，仍可查看索引和缓存封面。':current?.rel||'浏览此资源目录中的图片、视频和文件夹集合。'):query.actress?`按女优筛选：${query.actress} 的全部作品。`:`连接 ${data.roots.length} 个资源目录，让每一段画面都有迹可循。`:'连接本地文件夹，发现你的每一段影像。'}</p></div><div className="page-actions">{view==='library'&&<button className="secondary" onClick={()=>{if(current)void window.vm.refreshRoot(current.rootId).catch(e=>notify(String(e)));else refresh()}}><RefreshCw size={15} className={activeTasks.length?'spin-slow':''}/>刷新</button>}{view!=='library'&&<button className="secondary" onClick={refresh}><RefreshCw size={15} className={activeTasks.length?'spin-slow':''}/>刷新列表</button>}<button className="primary" onClick={()=>void addRoot()}><Plus size={16}/>添加目录</button></div></div>
   {view==='library'&&<div className={"toolbar"+(count>0?" has-selection":"")}><div className="browse-tools"><select className="scope-compact" aria-label="浏览范围" value={query.folderId?query.scope:"library"} onChange={event=>setQuery({scope:event.target.value as typeof query.scope})}>{query.folderId&&<><option value="direct">当前目录</option><option value="descendants">包含子目录</option></>}<option value="library">整个媒体库</option></select><div className="segmented scope-switch">{query.folderId?<><button className={query.scope==='direct'?'selected':''} onClick={()=>setQuery({scope:'direct'})}>当前目录</button><button className={query.scope==='descendants'?'selected':''} onClick={()=>setQuery({scope:'descendants'})}>包含子目录</button><button className={query.scope==='library'?'selected':''} onClick={()=>setQuery({scope:'library'})}>整个媒体库</button></>:<span className="scope-label"><Library size={14}/>整个媒体库</span>}</div><div className="type-filter"><button className={!query.kinds.length?'selected':''} onClick={()=>setQuery({kinds:[]})}>全部</button><button className={query.kinds.includes('image')?'selected':''} onClick={()=>setQuery({kinds:query.kinds.includes('image')?[]:['image']})}><ImageIcon size={15}/>图片</button><button className={query.kinds.includes('video')?'selected':''} onClick={()=>setQuery({kinds:query.kinds.includes('video')?[]:['video']})}><Film size={15}/>视频</button></div></div><div className="toolbar-spacer"/>
    {count>0&&<div className="selection-actions" role="group" aria-label="选中项操作"><span className="selection-count" title={`已选中 ${count.toLocaleString()} 项${snapshot?'（固定结果快照）':''}`}><Check size={14}/><span>已选 <strong>{count.toLocaleString()}</strong> 项</span></span><span className="selection-actions-divider"/><IconButton label="收藏选中项" onClick={()=>void window.vm.organize(selection(),'favorite',true).then(()=>{notify('已收藏选中项');refresh()}).catch(e=>notify(String(e)))}><Star size={16}/></IconButton><IconButton label="编辑选中项标签" onClick={()=>setOrganize({selection:selection(),entry:null})}><Tag size={16}/></IconButton><IconButton label="刮削选中视频的元数据" onClick={()=>{if(!data?.settings.scrapeEnabled){notify('请先在「设置 → 视频刮削」中启用刮削');return}void window.vm.scrapeRun(selection()).then(()=>notify('已开始后台刮削，可在后台任务中查看进度')).catch(e=>notify(String(e)))}}><Clapperboard size={16}/></IconButton><IconButton label="移动选中项" onClick={()=>setOperation({kind:'move',selection:selection(),entry:null})}><FolderInput size={16}/></IconButton><IconButton label="将选中项移入回收站" onClick={()=>setOperation({kind:'trash',selection:selection(),entry:null})}><Trash2 size={16}/></IconButton><span className="selection-actions-divider"/><IconButton label="取消选择 (Esc)" onClick={()=>select([])}><X size={15}/></IconButton></div>}
    <FilterPopover tags={data.tags}/><select aria-label="排序方式" value={query.sort+'-'+query.direction} onChange={e=>{const [sort,direction]=e.target.value.split('-');setQuery({sort:sort as typeof query.sort,direction:direction as 'asc'|'desc'})}}><option value="name-asc">名称 ↑</option><option value="name-desc">名称 ↓</option><option value="mtime-desc">最近修改</option><option value="size-desc">文件大小 ↓</option><option value="duration-desc">视频时长 ↓</option></select><div className="view-toggle"><IconButton label="卡片网格" active={layout==='grid'} onClick={()=>void switchLayout('grid')}><LayoutGrid size={17}/></IconButton><IconButton label="详细列表" active={layout==='list'} onClick={()=>void switchLayout('list')}><List size={19}/></IconButton></div></div>}
   {view==='library'&&(query.text||query.tags.length>0||query.favorite||query.actress||query.extensions.length>0)&&<div className="filter-chips">{query.text&&<span>包含 “{query.text}”</span>}{query.favorite&&<span><Star size={12}/>仅收藏</span>}{query.actress&&<span><Users size={12}/>{query.actress}</span>}{query.tags.map(t=><span key={t}><Tag size={12}/>{t}</span>)}{query.extensions.map(e=><span key={e}>{e}</span>)}<button className="text-button" onClick={()=>{setQuery({...defaultQuery,folderId:query.folderId,scope:query.scope});setSearch('')}}><X size={13}/>清空筛选</button></div>}
   {pendingUpdates&&<div className="update-banner">媒体库内容已更新，当前选择保持不变。<button onClick={refresh}>刷新显示</button></div>}
   {view==='movies'?<ViewBoundary onReset={()=>useNavigation.getState().back()}><MoviesView cardWidth={Number(data.settings.cardWidth??240)} fit={String(data.settings.fit??'cover')} initialSort={String(data.settings.movieSort??'recent-desc')} epoch={epoch} onOpen={openMovie} notify={notify}/></ViewBoundary>:view==='actresses'?<ViewBoundary onReset={()=>useNavigation.getState().back()}><ActressView cardWidth={Number(data.settings.cardWidth??240)} fit={String(data.settings.fit??'cover')} initialSort={String(data.settings.actressSort??'work-desc')} epoch={epoch} scrapeEnabled={!!data.settings.scrapeEnabled} notify={notify}/></ViewBoundary>:!data.roots.length?<div className="empty-state welcome"><AuroraScope/><Sparkles count={46}/><div className="welcome-inner"><div className="empty-art"><div className="art-sheet sheet-back"><Film size={38}/></div><div className="art-sheet sheet-front"><ImageIcon size={52} strokeWidth={1}/><span/><span/></div><div className="art-folder"><FolderOpen size={55} strokeWidth={1}/></div></div><span className="eyebrow">A SPACE FOR YOUR MOMENTS</span><h2><TextReveal text="让本地影像，清晰有序"/></h2><p>连接文件夹，以封面认识目录。<br/>在图片与视频间连续浏览，无需导入副本。</p><button className="primary large" onClick={()=>void addRoot()}><FolderPlus size={19}/>添加第一个资源目录</button><div className="welcome-features"><span><HardDrive size={15}/>保留原文件结构</span><span><MonitorPlay size={15}/>图片与视频统一浏览</span><span><Star size={15}/>收藏与标签整理</span></div></div></div>:sessionQuery.isError?<div className="empty-state"><h2>暂时无法读取内容</h2><p>{String(sessionQuery.error)}</p><button className="primary" onClick={refresh}>重新加载</button></div>:!session?<Busy label="正在读取目录…"/>:<ViewBoundary onReset={()=>void switchLayout('list')}><Viewport session={session} layout={layout} cardWidth={Number(data.settings.cardWidth??240)} fit={String(data.settings.fit??'cover')} onAction={action} onOpen={open} onSelectionError={notify}/></ViewBoundary>}
   <footer className="statusbar"><span><span className={'status-dot '+(activeTasks.length?'scanning':'online')}/>{activeTasks.length?`${activeTasks.length} 项后台任务进行中`:'媒体库已就绪'}</span><span>{view!=='library'?'':session?`${session.folders.toLocaleString()} 个文件夹 · ${session.media.toLocaleString()} 项媒体`:''}{session&&!session.complete?' · 索引未完成':''}</span><span>{view==='movies'?'点击电影卡片弹出播放窗口':view==='actresses'?'点击演员卡片查看其作品集合':count?`${count.toLocaleString()} 项已选中`:'双击打开 · 空格预览 · Ctrl 多选'}</span></footer>
  </main>
  {toast&&<div className="toast" role="status"><Info size={17}/><span>{toast}</span><button className="icon-button" aria-label="关闭通知" onClick={()=>setToast('')}><X size={15}/></button></div>}
  {add&&<Modal title="添加资源目录" description="应用将读取此目录及其后代的图片和视频，只保存索引与封面，不复制或改动原文件。" onClose={()=>{if(!adding)setAdd(null)}}><div className="confirm-path"><Folder size={20}/>{add.path}</div><div className="notice-box"><strong>默认排除</strong><p>隐藏目录、系统目录、符号链接／目录联接，以及应用自己的数据目录。</p></div>{add.overlaps.length>0&&<div className="notice-box"><strong>合并纳管</strong><p>将现有根目录 {add.overlaps.join('、')} 纳入此目录。原条目 ID、标签、收藏和手动封面将保留。</p></div>}<footer className="modal-footer"><button className="secondary" disabled={adding} onClick={()=>setAdd(null)}>取消</button><button className="primary" disabled={adding} onClick={async()=>{setAdding(true);try{const root=await window.vm.addRoot(add.grant);setAdd(null);navigate(root.entryId);refresh();notify('资源目录已添加，正在后台索引')}catch(e){notify(String(e))}finally{setAdding(false)}}}>{adding?'正在连接…':'添加并开始浏览'}</button></footer></Modal>}
  {preview&&<QuickPreview entry={preview} onClose={()=>setPreview(null)} onEnter={entry=>{setPreview(null);navigate(entry.id)}} onAction={action}/>}
  {viewer&&<Viewer player={videoPlayer} initial={viewer.entry} session={viewer.session} ordinal={viewer.index} onClose={()=>setViewer(null)} onLocate={locate} onCover={(entry,time)=>{setViewer(null);setCover({entry,time})}} notify={notify}/>}
  {cover&&<CoverEditor defaultQuality={(data.settings.coverQuality??defaultCoverQuality) as CoverQuality} target={cover.entry} initialTime={cover.time} onClose={()=>setCover(null)} onSaved={entry=>{replaceEntry(entry);setCover(null)}} notify={notify}/>}
  {scrape&&<ScrapeModal entry={scrape} onClose={()=>setScrape(null)} onApplied={()=>void client.invalidateQueries({queryKey:['bootstrap']})} notify={notify}/>}
  {showSettings&&<Settings data={data} onClose={()=>setShowSettings(false)} refresh={()=>void client.invalidateQueries({queryKey:['bootstrap']})} notify={notify} onAdd={()=>void addRoot()}/>}
  {showTasks&&<Tasks tasks={allTasks} onClose={()=>setShowTasks(false)} notify={notify}/>}
  {organize&&<TagDialog selected={organize.selection} entry={organize.entry} tags={data.tags} onClose={()=>setOrganize(null)} onDone={()=>{setOrganize(null);refresh();notify('标签已更新')}} notify={notify}/>}
  {showTags&&<TagOverviewModal tags={data.tags} active={query.tags} onClose={()=>setShowTags(false)} onPick={tag=>{setShowTags(false);navigate(null,'library',{...defaultQuery,tags:[tag]})}}/>}
  {operation&&<OperationDialog {...operation} roots={data.roots} current={current??null} onClose={()=>setOperation(null)} notify={notify} onDone={()=>{setOperation(null);select([]);setShowTasks(true);refresh()}}/>}
 </div>
}

function RootNode({root,current,ancestors,mode,epoch,onNavigate}:{root:Root;current:string|null;ancestors:Entry[];mode:string;epoch:number;onNavigate:(id:string)=>void}){const [expanded,setExpanded]=useState(true);const active=ancestors.some(e=>e.id===root.entryId);return <div className="root-node"><div className={'root-line '+(current===root.entryId?'selected':'')}><button className="tree-chevron" aria-expanded={expanded} aria-label={(expanded?'折叠 ':'展开 ')+root.name} onClick={()=>setExpanded(v=>!v)}>{expanded?<ChevronDown size={13}/>:<ChevronRight size={13}/>}</button><button className="tree-target" onClick={()=>onNavigate(root.entryId)}><HardDrive size={16}/><span>{root.name}</span><span className={'status-dot '+root.state}/></button></div>{expanded&&mode==='tree'&&<TreeChildren id={root.entryId} depth={1} current={current} ancestors={ancestors} epoch={epoch} onNavigate={onNavigate}/>}</div>}
function TreeChildren({id,depth,current,ancestors,epoch,onNavigate}:{id:string;depth:number;current:string|null;ancestors:Entry[];epoch:number;onNavigate:(id:string)=>void}){const children=useQuery({queryKey:['tree',id,epoch],queryFn:()=>window.vm.children(id),staleTime:Infinity,placeholderData:previous=>previous});const [expanded,setExpanded]=useState<Record<string,{open:boolean;location:string|null}>>({});return <>{children.data?.slice(0,200).map(e=>{const ancestor=ancestors.some(a=>a.id===e.id);const override=expanded[e.id];const open=override?(override.open||(override.location!==current&&ancestor)):ancestor;return <React.Fragment key={e.id}><div className={'tree-line '+(current===e.id?'selected':'')} style={{paddingLeft:depth*12+4}}><button className="tree-chevron" aria-expanded={open} aria-label={(open?'折叠 ':'展开 ')+e.name} onClick={()=>setExpanded(values=>({...values,[e.id]:{open:!open,location:current}}))}>{open?<ChevronDown size={12}/>:<ChevronRight size={12}/>}</button><button className="tree-target" onClick={()=>onNavigate(e.id)}><Folder size={15}/><span>{e.name}</span></button></div>{open&&depth<12&&<TreeChildren id={e.id} depth={depth+1} current={current} ancestors={ancestors} epoch={epoch} onNavigate={onNavigate}/>}</React.Fragment>})}</>}
function PathCrumb({entry,current,onNavigate}:{entry:Entry;current:boolean;onNavigate:(id:string)=>void}){const [open,setOpen]=useState(false);const children=useQuery({queryKey:['path-children',entry.id],queryFn:()=>window.vm.children(entry.id),enabled:open,staleTime:5000});return <span className={'path-crumb '+(current?'current':'')}><button title={entry.name} onClick={()=>onNavigate(entry.id)}>{entry.name}</button><Popover.Root open={open} onOpenChange={setOpen}><Popover.Trigger asChild><button aria-label={'展开 '+entry.name+' 的子目录'}><ChevronDown size={13}/></button></Popover.Trigger><Popover.Portal><Popover.Content className="path-popover" sideOffset={12} align="start"><h4>{entry.name} 的子文件夹</h4><div>{children.data?.map(e=><button key={e.id} onClick={()=>{onNavigate(e.id);setOpen(false)}}><Thumb entry={e}/><span>{e.name}</span><small>{e.subtree} 项媒体</small></button>)}{children.data?.length===0&&<p className="muted">没有子文件夹</p>}</div></Popover.Content></Popover.Portal></Popover.Root></span>}
function SearchFieldPicker(){const fields=useNavigation(s=>s.query.searchFields);const setQuery=useNavigation(s=>s.setQuery);const options=[['name','文件名'],['folder','文件夹名'],['tag','标签名']] as const;return <Popover.Root><Popover.Trigger asChild><button className={'search-field-trigger '+(fields.length<3?'active':'')} aria-label="选择搜索范围" title="选择搜索范围"><SlidersHorizontal size={14}/></button></Popover.Trigger><Popover.Portal><Popover.Content className="search-field-popover" sideOffset={10} align="end"><strong>搜索范围</strong><small>默认同时搜索以下全部字段</small>{options.map(([id,label])=><label key={id}><input type="checkbox" checked={fields.includes(id)} onChange={event=>setQuery({searchFields:event.target.checked?[...fields,id]:fields.filter(field=>field!==id)})}/><span>{label}</span></label>)}</Popover.Content></Popover.Portal></Popover.Root>}
function QuickPreview({entry,onClose,onEnter,onAction}:{entry:Entry;onClose:()=>void;onEnter:(e:Entry)=>void;onAction:(action:EntryAction,e:Entry,index?:number)=>void}){const data=useQuery({queryKey:['quick',entry.id],queryFn:async()=>{const q=await window.vm.openQuery({...defaultQuery,folderId:entry.id,scope:'direct'});const media=await window.vm.page(q.id,q.folders,12);return {media:media.entries,folders:await window.vm.children(entry.id)}}});return <Modal title={entry.name} description="快速预览不会改变当前浏览位置。" onClose={onClose}><div className="preview-cover"><Thumb entry={entry}/></div><div className="preview-stats"><span><ImageIcon size={16}/>{entry.directImages} 张图片</span><span><Film size={16}/>{entry.directVideos} 个视频</span><span><Folder size={16}/>{entry.directFolders} 个目录</span></div><p className="muted">含后代媒体 {entry.subtree} 项 · 其他文件 {entry.other} 项</p><div className="preview-grid">{data.data?.media.map(e=><button key={e.id} onClick={()=>onAction('preview',e)}><Thumb entry={e}/><span>{e.name}</span></button>)}</div><div className="preview-folders">{data.data?.folders.map(e=><button key={e.id} className="secondary" onClick={()=>onEnter(e)}><Folder size={15}/>{e.name}</button>)}</div><footer className="modal-footer"><button className="secondary" onClick={()=>onAction('cover',entry)}><ImagePlus size={16}/>设置封面</button><button className="primary" onClick={()=>onEnter(entry)}>进入文件夹<ChevronRight size={16}/></button></footer></Modal>}
function TagDialog({selected,entry,tags,onClose,onDone,notify}:{selected:Selection;entry:Entry|null;tags:Bootstrap['tags'];onClose:()=>void;onDone:()=>void;notify:(m:string)=>void}){const [text,setText]=useState('');const [busy,setBusy]=useState(false);const apply=async(action:'tag-add'|'tag-remove',value:string)=>{setBusy(true);try{for(const tag of value.split(/[,，]/).map(t=>t.trim()).filter(Boolean))await window.vm.organize(selected,action,tag);onDone()}catch(e){notify(String(e));setBusy(false)}};return <Modal title="编辑标签" description="标签不会写入原文件，也不会自动继承给目录中的媒体。" onClose={onClose}>{entry&&<div className="tag-pills">{entry.tags.map(tag=><button key={tag} onClick={()=>void apply('tag-remove',tag)}>{tag}<X size={13}/></button>)}</div>}<label className="field">添加标签（多个标签以逗号分隔）<input autoFocus value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&text.trim())void apply('tag-add',text)}} placeholder="旅行、灵感、待整理…"/></label><div className="tag-pills">{tags.map(tag=><button key={tag.name} onClick={()=>setText(text?text+','+tag.name:tag.name)}><Tag size={12}/>{tag.name}</button>)}</div><footer className="modal-footer"><button className="secondary" disabled={!text.trim()||busy} onClick={()=>void apply('tag-remove',text)}>移除这些标签</button><button className="primary" disabled={!text.trim()||busy} onClick={()=>void apply('tag-add',text)}>应用标签</button></footer></Modal>}
function TagOverviewModal({tags,active,onClose,onPick}:{tags:Bootstrap['tags'];active:string[];onClose:()=>void;onPick:(tag:string)=>void}){
 const [search,setSearch]=useState('')
 const mediaTotal=tags.reduce((sum,tag)=>sum+tag.count,0)
 const list=[...tags].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'zh-CN')).filter(tag=>tag.name.toLowerCase().includes(search.toLowerCase()))
 return <Modal title="标签" description="展示全部标签及其对应的媒体数量；点击任意标签即可查看该标签下的视频集合。" onClose={onClose} wide>
  <div className="tag-overview">
   <div className="tag-overview-head">
    <span className="tag-overview-stat"><strong>{tags.length}</strong> 个标签 · 覆盖 <strong>{mediaTotal.toLocaleString()}</strong> 项媒体标注</span>
   </div>
   {tags.length>12&&<div className="tag-overview-search"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="查找标签…" autoFocus/></div>}
   <div className="tag-overview-list">{list.map(tag=><button key={tag.name} className={active.includes(tag.name)?'selected':''} title={`${tag.name} · ${tag.count} 个媒体`} onClick={()=>onPick(tag.name)}>
     <span className="tag-color"/><span className="tag-overview-name">{tag.name}</span>
     <span className="tag-overview-count"><small>{tag.count}</small></span>
    </button>)}
    {!tags.length&&<div className="tag-overview-empty"><Tags size={30} strokeWidth={1.2}/><p>还没有任何标签</p><small>选中媒体后可添加标签，视频刮削到的标签也会自动并入这里。</small></div>}
    {!!tags.length&&!list.length&&<div className="tag-overview-empty"><Tags size={30} strokeWidth={1.2}/><p>没有匹配的标签</p><small>换个关键字试试。</small></div>}
   </div>
   {!!tags.length&&<footer className="modal-footer"><span className="muted">按数量排序 · 点击标签查看对应视频集合</span></footer>}
  </div>
 </Modal>
}
function OperationDialog({kind,selection:chosen,entry,roots,current,onClose,onDone,notify}:{kind:'rename'|'move'|'trash';selection:Selection;entry:Entry|null;roots:Root[];current:Entry|null;onClose:()=>void;onDone:()=>void;notify:(m:string)=>void}){
 const titles={rename:'重命名',move:'移动到文件夹',trash:'移入系统回收站'} as const
 const descriptions={rename:'实际文件位置将发生变化，标签、收藏与手动封面关联会保留。',move:'实际文件位置将发生变化，标签、收藏与手动封面关联会保留。',trash:'确认后将影响所选文件夹内的全部内容，包括隐藏文件和非媒体文件。回收站失败时不会永久删除。'} as const
 const ext=entry&&entry.kind!=='folder'&&entry.name.includes('.')?'.'+entry.name.split('.').pop():''
 const [name,setName]=useState(entry?entry.name.slice(0,ext?-ext.length:undefined):'');const [target,setTarget]=useState<Entry|null>(current);const [conflict,setConflict]=useState<'keep'|'skip'>('keep');const [plan,setPlan]=useState<Plan|null>(null);const [busy,setBusy]=useState(false)
 const dirs=useQuery({queryKey:['move-dirs',target?.id],queryFn:()=>window.vm.children(target!.id),enabled:kind==='move'&&!!target})
 const getPlan=async()=>{setBusy(true);try{setPlan(await window.vm.plan(chosen,kind,target?.id??null,kind==='rename'?name+ext:null,conflict))}catch(e){notify(String(e))}finally{setBusy(false)}}
 useEffect(()=>{if(kind==='trash')void getPlan()},[])
 return <Modal title={titles[kind]} description={descriptions[kind]} onClose={()=>{if(!busy)onClose()}}>{!plan&&kind==='rename'&&<label className="field">新名称<input autoFocus value={name} onChange={e=>setName(e.target.value)}/>{ext&&<small>扩展名 {ext} 将保留</small>}</label>}{!plan&&kind==='move'&&<><label className="field">选择已纳管的目标目录<select value={target?.rootId??''} onChange={e=>{const root=roots.find(r=>r.id===e.target.value);if(root)void window.vm.entry(root.entryId).then(setTarget)}}><option value="">选择资源根目录</option>{roots.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{target&&<div className="destination-path"><button className="icon-button" disabled={!target.parentId} aria-label="目标上一级" onClick={()=>{if(target.parentId)void window.vm.entry(target.parentId).then(setTarget)}}><ArrowUp size={15}/></button><FolderOpen size={16}/>{target.rel||target.name}</div>}<div className="destination-list">{dirs.data?.map(e=><button key={e.id} onClick={()=>setTarget(e)}><Folder size={17}/>{e.name}<ChevronRight size={15}/></button>)}{!dirs.data?.length&&<p className="muted">此目录没有子文件夹，可选为目标。</p>}</div></>}{!plan&&kind!=='trash'&&<label className="field">遇到同名目标<select value={conflict} onChange={e=>setConflict(e.target.value as 'keep'|'skip')}><option value="keep">保留两者（为新项目添加序号）</option><option value="skip">跳过同名项目</option></select></label>}{busy&&<Busy label="正在核验实际文件范围…"/>}{plan&&<><p className="notice-box">{plan.message}</p><div className="operation-items">{plan.items.map(item=><article key={item.id}><strong>{item.name}{item.conflict&&<span className="badge">同名 · 跳过</span>}</strong><small>{item.source}</small>{item.destination&&<small>→ {item.destination}</small>}<span>{item.files} 个文件 · {item.folders} 个目录 · {formatSize(item.bytes)}</span></article>)}</div><p className="muted">共 {plan.items.length} 个顶层项目；批量操作可逐项成功，已完成的项目不会因取消而回滚。</p></>}<footer className="modal-footer"><button className="secondary" disabled={busy} onClick={onClose}>取消</button>{plan?<button className={kind==='trash'?'danger-button':'primary'} disabled={busy} onClick={async()=>{setBusy(true);try{await window.vm.commit(plan.id);onDone()}catch(e){notify(String(e));setBusy(false)}}}>{kind==='trash'?'确认移入回收站':'确认执行'}</button>:<button className="primary" disabled={busy||(kind==='move'&&!target)||(kind==='rename'&&!name.trim())} onClick={()=>void getPlan()}>检查并预览操作</button>}</footer></Modal>}

createRoot(document.getElementById('root')!).render(<QueryClientProvider client={client}><App/></QueryClientProvider>)
