import { memo,useEffect,useRef,useState,type MouseEvent } from 'react'
import { useQueries } from '@tanstack/react-query'
import { useVirtualizer } from '@tanstack/react-virtual'
import { Folder,Film,Image as ImageIcon,Star,Eye } from 'lucide-react'
import type { Entry,Page,QuerySession } from '../../../../packages/contracts'
import { Thumb,EntryMenu,SelectionMark,formatSize,formatTime,type EntryAction } from './components'
import { useNavigation } from './store'
import {useDetailColumns} from './DetailColumns'

export const Viewport=memo(function Viewport({session,layout,cardWidth,fit,onAction,onOpen,onSelectionError}:{session:QuerySession;layout:string;cardWidth:number;fit:string;onAction:(action:EntryAction,e:Entry,index?:number)=>void;onOpen:(e:Entry,index:number)=>void;onSelectionError:(message:string)=>void}){
 const [contextEntry,setContextEntry]=useState<{id:string;x:number;y:number}|null>(null);const scroll=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(900);const selected=useNavigation(s=>s.selected);const snapshot=useNavigation(s=>s.snapshot);const query=useNavigation(s=>s.query);const select=useNavigation(s=>s.select);const lastIndex=useRef(0);const selectedRef=useRef(selected);selectedRef.current=selected
 const detail=useDetailColumns()
 const grid=layout==='grid';const columns=grid?Math.max(1,Math.floor((width-48+16)/(cardWidth+16))):1;const folderRows=Math.ceil(session.folders/columns);const mediaRows=Math.ceil(session.media/columns);const hasFolders=session.folders>0;const mediaStart=(hasFolders?folderRows+1:0);const rowCount=mediaStart+1+mediaRows;const itemWidth=(width-48-(columns-1)*16)/columns;const height=grid?Math.round(itemWidth/1.6)+74:48
 const describe=(row:number)=>{if(hasFolders&&row===0)return {header:'folder',offset:0,count:0};if(row===mediaStart)return {header:'media',offset:0,count:0};if(hasFolders&&row<mediaStart){const offset=(row-1)*columns;return {header:'',offset,count:Math.min(columns,session.folders-offset)}}const offset=session.folders+(row-mediaStart-1)*columns;return {header:'',offset,count:Math.min(columns,session.total-offset)}}
 const virtual=useVirtualizer({count:rowCount,scrollMargin:grid?0:42,getScrollElement:()=>scroll.current,estimateSize:i=>describe(i).header?46:height,overscan:grid?3:10})
 const visible=virtual.getVirtualItems();const pages=[...new Set(visible.flatMap(row=>{const d=describe(row.index);return Array.from({length:d.count},(_,i)=>Math.floor((d.offset+i)/100))}))]
 const pageQueries=useQueries({queries:pages.map(page=>({queryKey:['page',session.id,page],queryFn:()=>window.vm.page(session.id,page*100,100),staleTime:600000,gcTime:30000,retry:false,placeholderData:(previous:Page|undefined)=>previous}))})
 const entries=new Map<number,Entry>();for(const q of pageQueries)if(q.data)q.data.entries.forEach((e,i)=>entries.set(q.data!.offset+i,e))
 useEffect(()=>{const el=scroll.current;if(!el)return;const resize=new ResizeObserver(records=>{const next=Math.round(records[0]?.contentRect.width??900);setWidth(current=>current===next?current:next)});resize.observe(el);return()=>resize.disconnect()},[])
 useEffect(()=>{virtual.measure()},[height,columns,rowCount])
 useEffect(()=>{let active=true;const state=useNavigation.getState();const restore=(index:number)=>{if(!active)return;if(index===0){virtual.scrollToOffset(0);return}const row=index<session.folders?(hasFolders?1:0)+Math.floor(index/columns):mediaStart+1+Math.floor((index-session.folders)/columns);virtual.scrollToIndex(Math.min(row,rowCount-1),{align:'start'})};if(state.anchorId)void window.vm.position(session.id,state.anchorId).then(index=>restore(index??state.anchor)).catch(()=>restore(state.anchor));else restore(state.anchor);return()=>{active=false}},[session.id,grid,columns])
 useEffect(()=>{const first=visible.find(r=>!describe(r.index).header);if(first){const d=describe(first.index);const e=entries.get(d.offset);if(e)useNavigation.getState().setAnchor(d.offset,e.id)}},[visible[0]?.index])
 const toggle=(e:Entry,index:number)=>{select(selected.includes(e.id)?selected.filter(id=>id!==e.id):[...selected,e.id]);lastIndex.current=index}
 async function choose(e:Entry,index:number,event:MouseEvent){if(event.shiftKey){const from=Math.min(lastIndex.current,index),to=Math.max(lastIndex.current,index);if(to-from>10000){onSelectionError('范围过大，请使用 Ctrl+A 冻结整个结果集');return}try{const ids:string[]=[];for(let i=from;i<=to;i+=200){const page=await window.vm.page(session.id,i,Math.min(200,to-i+1));ids.push(...page.entries.map(e=>e.id))}select(ids)}catch(error){onSelectionError(String(error))}}else if(event.ctrlKey||event.metaKey)toggle(e,index);else{select(selected.includes(e.id)&&selected.length===1?[]:[e.id]);lastIndex.current=index}}
 const keyboard=async(event:React.KeyboardEvent)=>{const target=event.target as HTMLElement;if(target.closest('button,input,select,[role=separator]'))return;let index=lastIndex.current;if(event.key==='ArrowRight')index++;else if(event.key==='ArrowLeft')index--;else if(event.key==='ArrowDown')index+=columns;else if(event.key==='ArrowUp')index-=columns;else if(event.key==='Enter'||event.code==='Space'){const e=entries.get(index)??(await window.vm.page(session.id,index,1)).entries[0];if(e){event.preventDefault();if(event.code==='Space')onAction('preview',e,index);else onOpen(e,index)}return}else return;event.preventDefault();index=Math.max(0,Math.min(session.total-1,index));lastIndex.current=index;const e=(await window.vm.page(session.id,index,1)).entries[0];if(e){select([e.id]);const row=index<session.folders?1+Math.floor(index/columns):mediaStart+1+Math.floor((index-session.folders)/columns);virtual.scrollToIndex(row,{align:'auto'});scroll.current?.focus()}}
 return <div className={'viewport '+(grid?'grid-view':'list-view')+' fit-'+fit} ref={scroll} tabIndex={0} aria-label="媒体浏览区" onKeyDown={event=>void keyboard(event).catch(e=>onSelectionError(String(e)))}>
  <div className={grid?undefined:"list-table"} style={grid?undefined:{minWidth:detail.minWidth+48}}>
  {!grid&&detail.header}
  <div style={{height:virtual.getTotalSize(),position:'relative'}}>
  {visible.map(row=>{const d=describe(row.index);return <div key={row.key} className={'virtual-row '+(d.header?'section-heading':'')} style={{position:'absolute',top:0,left:24,right:24,height:row.size,transform:`translateY(${row.start-(grid?0:42)}px)`,...(d.header?{}:{display:'grid',gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`,gap:16})}}>
   {d.header?<><h2>{d.header==='folder'?<Folder size={17}/>:<ImageIcon size={17}/>} {d.header==='folder'?'文件夹集合':query.scope==='direct'?'当前目录媒体':'全部媒体'}<span>{(d.header==='folder'?session.folders:session.media).toLocaleString()}</span></h2><small>{d.header==='folder'?'直接子文件夹':query.scope==='descendants'?'包含所有后代目录 · 保留来源路径':!session.complete?'索引仍在进行，结果可能不完整':''}</small></>:Array.from({length:d.count},(_,col)=>{const index=d.offset+col;const e=entries.get(index);if(!e)return <div className="card skeleton" key={index}/>;const picked=!!snapshot||selected.includes(e.id);return <div key={e.id} role="option" aria-selected={picked} aria-label={e.name} style={grid?undefined:{gridTemplateColumns:detail.template}} className={(grid?'card':'list-item')+(picked?' selected':'')+(e.state!=='present'?' unavailable':'')} onClick={event=>void choose(e,index,event)} onDoubleClick={()=>onOpen(e,index)} onContextMenu={event=>{event.preventDefault();if(!selected.includes(e.id)&&!snapshot)select([e.id]);setContextEntry({id:e.id,x:event.clientX,y:event.clientY})}}>
    {grid&&<><div className="card-image"><Thumb entry={e}/><><SelectionMark selected={picked} label={`${picked?'取消选择':'选择'} ${e.name}`} onToggle={()=>toggle(e,index)}/>{e.kind==='video'&&<span className="duration"><Film size={11}/>{formatTime(e.duration)}</span>}{e.kind==='folder'&&<span className="folder-badge"><Folder size={12}/>文件夹</span>}{e.favorite>0&&<span className="favorite-badge"><Star size={13} fill="currentColor"/></span>}{e.rootState==='offline'&&<span className="offline-badge">离线</span>}</></div>
    <div className="card-info"><div className="card-title"><span title={e.name}>{e.name}</span></div>{grid&&<div className="card-subtitle">{e.kind==='folder'?<span>{e.complete?`${e.directImages} 张图片 · ${e.directVideos} 个视频 · ${e.directFolders} 个目录`:'统计中…'}</span>:<><span>{query.scope!=='direct'?(e.rel.includes('/')?e.rel.slice(0,e.rel.lastIndexOf('/')):'根目录'):e.ext.toUpperCase()+' · '+formatSize(e.size)}</span>{e.tags.length>0&&<span className="tag-dot">{e.tags[0]}</span>}</>}</div>}</div>
    </>}
    {!grid&&detail.columns.map(column=><div key={column.id} className={'list-cell list-cell-'+column.id}>
     {column.id==='name'?<><SelectionMark selected={picked} label={`${picked?'取消选择':'选择'} ${e.name}`} onToggle={()=>toggle(e,index)}/><div className="list-thumbnail"><Thumb entry={e}/></div><span className="list-name" title={e.name}>{e.name}</span>{e.favorite>0&&<Star className="list-favorite" size={13} fill="currentColor"/>}</>:column.id==='type'?(e.kind==='folder'?'文件夹':e.ext.toUpperCase()):column.id==='duration'?(e.kind==='video'?formatTime(e.duration):'—'):column.id==='size'?(e.kind==='folder'?'—':formatSize(e.size)):new Date(e.mtime).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
    </div>)}
    <div className="card-actions">{grid&&e.kind==='folder'&&<button className="icon-button quick-view" aria-label={'预览 '+e.name} onClick={event=>{event.stopPropagation();onAction('preview',e,index)}}><Eye size={16}/></button>}<EntryMenu entry={e} contextPosition={contextEntry?.id===e.id?contextEntry:undefined} closeContext={()=>setContextEntry(null)} onAction={(action,e)=>onAction(action,e,index)}/></div>
   </div>})}
  </div>})}
  </div>
  </div>
  {session.media===0&&<div className="inline-empty"><ImageIcon size={28}/><p>{query.text||query.favorite||query.tags.length?'当前条件下没有找到媒体':'当前目录暂无图片或视频'}</p>{session.folders>0&&<button className="text-button" onClick={()=>useNavigation.getState().setQuery({scope:'descendants'})}>查看全部子目录媒体 →</button>}</div>}
 </div>
})
