'use strict';
function takeInvitation(){const value=new URLSearchParams(location.hash.slice(1)).get('connect')||'';if(location.hash)history.replaceState(null,'',location.pathname+location.search);return value}
let initialInvitation=takeInvitation();
const $=id=>document.getElementById(id);
const paths={folder:'M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z',video:'M9 7l8 5-8 5Z M3 5h18v14H3Z',image:'M3 3h18v18H3Z M3 16l6-6 5 5 3-3 4 4 M16 7h.01',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',refresh:'M20 7v5h-5 M4 17v-5h5 M5 8a8 8 0 0 1 13-3l2 3 M4 16l2 3a8 8 0 0 0 13-3',close:'M6 6l12 12 M6 18L18 6',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',sun:'M12 3v2 M12 19v2 M3 12h2 M19 12h2 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0'};
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.6');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');svg.classList.add('icon');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.folder);svg.append(p);return svg}
function node(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n}
for(const [id,name]of [['theme','sun'],['pair-icon','link'],['search-icon','search'],['refresh','refresh'],['empty-icon','folder'],['close-viewer','close']])$(id).append(icon(name));
let session=null,entries=[],folderId=null,text='',kind='',total=0,controller=null,loadRound=0,viewerEntry=null,viewerList=[],viewRound=0,lastSaved=0,searchTimer;
function storageGet(key){try{return localStorage.getItem(key)}catch{return null}}
function storageSet(key,value){try{localStorage.setItem(key,value)}catch{}}
document.documentElement.dataset.theme=storageGet('vm-lan-theme')||(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark');
$('theme').onclick=()=>{const value=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=value;storageSet('vm-lan-theme',value)};
async function api(url,options={}){let response;try{response=await fetch(url,{...options,credentials:'same-origin'})}catch(e){if(e.name==='AbortError')throw e;throw Error('连接中断，请确认电脑保持开机、共享已开启，并检查网络连接。')}
 const body=await response.json();if(!response.ok){if(response.status===401&&session){disconnected('设备授权已过期或被撤销，请扫描电脑端的新二维码。')}const error=Error(body.error||'请求失败');error.status=response.status;throw error}return body}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function disconnected(message){session=null;closeViewer();controller?.abort();$('grid').replaceChildren();entries=[];$('library').hidden=true;$('pair').hidden=false;$('logout').hidden=true;$('connect-heading').textContent='扫码连接媒体空间';$('pair-error').textContent=message;$('connect-message').textContent='请扫描电脑「设置与插件 → 局域网共享」中的二维码。'}
function authenticated(value){session=value;$('pair').hidden=true;$('library').hidden=false;$('logout').hidden=false;$('pair-error').textContent='';$('device-label').textContent=value.name;const params=new URLSearchParams(location.search);folderId=params.get('folderId');text=params.get('text')||'';kind=['image','video'].includes(params.get('kind'))?params.get('kind'):'';$('search').value=text;$('kind').value=kind;void load()}
function deviceName(){const ua=navigator.userAgent;return /iPad/.test(ua)?'iPad':/iPhone/.test(ua)?'iPhone':/Android/.test(ua)?'Android 手机':/Windows/.test(ua)?'Windows 浏览器':/Macintosh/.test(ua)?'Mac 浏览器':'浏览器设备'}
let connecting=false;
async function connect(invitation=''){
 if(connecting)return;connecting=true;$('connect-heading').textContent='正在连接电脑…';$('connect-message').textContent='正在验证此设备的访问权限。';$('pair-error').textContent='';
 try{
  try{authenticated(await api('/api/session'));return}catch(error){if(error.status!==401)throw error}
  if(!invitation){disconnected('仅打开共享网址无法访问资源，请使用电脑端二维码。');return}
  authenticated(await post('/api/connect',{invitation,name:deviceName()}));
 }catch(error){disconnected(error.message)}finally{connecting=false;invitation=''}
}
$('logout').onclick=async()=>{try{await post('/api/logout',{});disconnected('此设备已退出。')}catch(error){$('connection').hidden=false;$('connection').textContent=error.message}};
function formatSize(size){return size>=1073741824?(size/1073741824).toFixed(1)+' GB':size>=1048576?(size/1048576).toFixed(1)+' MB':size>=1024?(size/1024).toFixed(0)+' KB':size+' B'}
function duration(seconds){if(!seconds)return '';const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return m+':'+String(s).padStart(2,'0')}
function mediaUrl(e,purpose){return '/api/media/'+encodeURIComponent(e.id)+'/'+purpose}
function updateUrl(replace=false){const params=new URLSearchParams();if(folderId)params.set('folderId',folderId);if(text)params.set('text',text);if(kind)params.set('kind',kind);const url='/'+(params.size?'?'+params:'');history[replace?'replaceState':'pushState']({},'',url)}
function navigate(id){folderId=id;text='';kind='';$('search').value='';$('kind').value='';updateUrl();void load()}
function card(e){const button=node('button','media-card');button.type='button';button.title=e.name;button.setAttribute('aria-label',e.name);button.disabled=!e.online&&e.kind!=='folder';const thumb=node('div','thumbnail');thumb.append(icon(e.kind));const image=node('img');image.loading='lazy';image.decoding='async';image.alt='';image.src=mediaUrl(e,'thumbnail')+'?v='+e.revision+'-'+e.coverRevision;let tries=0;image.onerror=()=>{if(tries++<2&&session&&button.isConnected)setTimeout(()=>{if(button.isConnected)image.src=mediaUrl(e,'thumbnail')+'?retry='+tries},600*tries);else image.remove()};thumb.append(image);const badge=node('span','media-badge',e.kind==='folder'?'目录':e.kind==='video'?duration(e.duration)||'视频':e.ext.toUpperCase());badge.prepend(icon(e.kind));thumb.append(badge);if(!e.online)thumb.append(node('span','offline','目录离线'));const info=node('div','media-info');info.append(node('strong','',e.name),node('small','',e.kind==='folder'?'打开查看目录':[formatSize(e.size),e.width&&e.height?e.width+' × '+e.height:'',e.tags.slice(0,2).join(' · ')].filter(Boolean).join(' · ')));button.append(thumb,info);button.onclick=()=>e.kind==='folder'?navigate(e.id):openViewer(e);return button}
async function load(append=false){if(!session)return;controller?.abort();controller=new AbortController();const round=++loadRound;$('loading').hidden=false;$('browse-error').textContent='';$('more').disabled=true;if(!append){entries=[];$('grid').replaceChildren();$('empty').hidden=true}
 const query=new URLSearchParams({text,kind,offset:String(entries.length),limit:'60'});if(folderId)query.set('folderId',folderId);
 try{const result=await api('/api/browse?'+query,{signal:controller.signal});if(round!==loadRound||!session)return;entries.push(...result.entries);total=result.total;const fragment=document.createDocumentFragment();result.entries.forEach(e=>fragment.append(card(e)));$('grid').append(fragment);$('breadcrumbs').replaceChildren();const home=node('button','','共享目录');home.onclick=()=>navigate(null);$('breadcrumbs').append(home);for(const folder of result.breadcrumbs){$('breadcrumbs').append(node('span','','/'));const b=node('button','',folder.name);b.onclick=()=>navigate(folder.id);$('breadcrumbs').append(b)}$('library-summary').textContent=text?'在共享范围内搜索「'+text+'」':'浏览目录中的图片与视频';$('count').textContent='已显示 '+entries.length+' / '+total+' 项';$('more').hidden=entries.length>=total;$('empty').hidden=total!==0;$('connection').hidden=true;
 }catch(error){if(error.name!=='AbortError'&&round===loadRound){$('browse-error').textContent=error.message;$('more').hidden=!append}}
 finally{if(round===loadRound){$('loading').hidden=true;$('more').disabled=false}}}
function search(){text=$('search').value.trim();kind=$('kind').value;updateUrl();void load()}
$('search-form').onsubmit=e=>{e.preventDefault();clearTimeout(searchTimer);search()};$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(search,350)};$('kind').onchange=search;$('refresh').onclick=()=>load();$('more').onclick=()=>load(true);window.onpopstate=()=>{const params=new URLSearchParams(location.search);folderId=params.get('folderId');text=params.get('text')||'';kind=params.get('kind')||'';$('search').value=text;$('kind').value=kind;void load()};
function progressKey(e){return 'vm-lan-progress:'+session.libraryKey+':'+e.id+':'+e.revision}
function saveProgress(force=false){const video=$('viewer-stage').querySelector('video');if(!viewerEntry||!session||!video||video.readyState<1||!Number.isFinite(video.duration)||video.duration<=0||!Number.isFinite(video.currentTime))return;if(!force&&Date.now()-lastSaved<3000)return;lastSaved=Date.now();storageSet(progressKey(viewerEntry),JSON.stringify({position:video.ended?0:video.currentTime,updated:Date.now()}))}
function cleanupMedia(){saveProgress(true);viewRound++;for(const video of $('viewer-stage').querySelectorAll('video')){video.pause();video.removeAttribute('src');video.load()}$('viewer-stage').replaceChildren();viewerEntry=null}
function closeViewer(){cleanupMedia();if($('viewer').open)$('viewer').close();if(session)void post('/api/playing',{entryId:null}).catch(()=>{})}
function openViewer(e){cleanupMedia();viewerEntry=e;viewerList=entries.filter(item=>item.kind!=='folder'&&item.online);const index=viewerList.findIndex(item=>item.id===e.id);$('viewer-title').textContent=e.name;$('viewer-meta').textContent=[formatSize(e.size),e.ext.toUpperCase(),e.width&&e.height?e.width+' × '+e.height:''].filter(Boolean).join(' · ');$('viewer-index').textContent=(index+1)+' / '+viewerList.length;$('previous').disabled=index<=0;$('next').disabled=index>=viewerList.length-1;$('viewer-error').hidden=true;const round=viewRound;
 if(e.kind==='image'){const image=node('img');image.alt=e.name;image.src=mediaUrl(e,'original');image.onclick=()=>image.classList.toggle('zoomed');image.onerror=()=>showViewerError('图片加载失败，请检查共享状态和目录是否在线。',round);$('viewer-stage').append(image);void post('/api/playing',{entryId:null}).catch(()=>{})}
 else{const video=node('video');video.controls=true;video.playsInline=true;video.preload='metadata';video.src=mediaUrl(e,'original');video.poster=mediaUrl(e,'thumbnail');video.onloadedmetadata=()=>{if(round!==viewRound||!session)return;try{const value=JSON.parse(storageGet(progressKey(e))||'null');if(value?.position>0&&value.position<video.duration-2)video.currentTime=value.position}catch{};video.play().catch(()=>{})};video.ontimeupdate=()=>saveProgress();video.onpause=()=>saveProgress(true);video.onended=()=>saveProgress(true);video.onerror=()=>showViewerError(video.error?.code===3||video.error?.code===4?'当前浏览器无法解码此视频。可尝试其他浏览器，或在电脑端使用 mpv 播放；本版本暂不转码。':'视频连接中断。请检查网络和电脑端共享状态，重新打开视频可继续观看。',round);$('viewer-stage').append(video);void post('/api/playing',{entryId:e.id}).catch(error=>showViewerError(error.message,round))}
 if(!$('viewer').open)$('viewer').showModal();$('close-viewer').focus()}
function showViewerError(message,round){if(round!==viewRound||!$('viewer').open)return;$('viewer-error').hidden=false;$('viewer-error').textContent=message}
$('close-viewer').onclick=closeViewer;$('viewer').addEventListener('cancel',e=>{e.preventDefault();closeViewer()});$('viewer').addEventListener('click',e=>{if(e.target===$('viewer')){const box=$('viewer').getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)closeViewer()}});
function step(delta){const index=viewerList.findIndex(item=>item.id===viewerEntry?.id);const target=viewerList[index+delta];if(target)openViewer(target)}$('previous').onclick=()=>step(-1);$('next').onclick=()=>step(1);
$('fullscreen').onclick=async()=>{const stage=$('viewer-stage'),video=stage.querySelector('video');try{if(document.fullscreenElement)await document.exitFullscreen();else if(stage.requestFullscreen)await stage.requestFullscreen();else if(video?.webkitEnterFullscreen)video.webkitEnterFullscreen();else throw Error()}catch{showViewerError('此浏览器的全屏能力有限，可使用视频控件中的全屏按钮。',viewRound)}};
window.addEventListener('pagehide',()=>saveProgress(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)saveProgress(true)});
setInterval(async()=>{if(!session||document.hidden)return;try{await api('/api/session');$('connection').hidden=true}catch(error){if(session){$('connection').hidden=false;$('connection').textContent=error.message}}},15000);
window.addEventListener('online',()=>{if(session)void load()});window.addEventListener('offline',()=>{if(session){$('connection').hidden=false;$('connection').textContent='网络已断开。恢复连接后可以刷新目录并继续观看。'}});
window.addEventListener('hashchange',()=>{const invitation=takeInvitation();if(invitation)void connect(invitation)});
void connect(initialInvitation);
initialInvitation='';
