import {_electron as electron} from 'playwright'
import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
const suffix=Date.now(),base=path.resolve('.test-data/e2e-'+suffix),source=path.join(base,'影像测试库'),userData=path.join(base,'app-data');await fs.mkdir(base,{recursive:true});await fs.cp(path.resolve('.test-data/fixtures'),source,{recursive:true});await fs.mkdir('test-results',{recursive:true})
const defaultQuery={folderId:null,scope:'library',text:'',kinds:[],extensions:[],tags:[],favorite:false,sort:'name',direction:'asc',minSize:null,maxSize:null,after:null,before:null,minDuration:null,maxDuration:null}
const results=[];const errors=[];let application,page
const log=(name,extra={})=>{results.push({name,passed:true,...extra});console.log('PASS',name,JSON.stringify(extra))}
async function api(method,...args){return page.evaluate(([method,args])=>window.vm[method](...args),[method,args])}
async function waitFor(fn,label,timeout=30000){const start=Date.now();while(Date.now()-start<timeout){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,150))}throw Error('Timeout: '+label)}
async function capture(name){await page.waitForTimeout(250);await page.screenshot({path:'test-results/'+name+'.png'})}
async function launch(){application=await electron.launch({executablePath:path.resolve(process.env.VM_TEST_EXECUTABLE||'node_modules/electron/dist/electron.exe'),args:process.env.VM_TEST_EXECUTABLE?[]:['.'],env:{...process.env,VM_DATA_DIR:userData,VM_TEST_HIDDEN:'1',...(!process.env.VM_TEST_EXECUTABLE?{VM_TEST_ROOT:source}:{})},timeout:30000});application.process().stderr.on('data',d=>{const s=String(d);if(!s.includes('Debugger')&&!s.includes('For help'))console.log(s.trim())});page=await application.firstWindow();page.on('pageerror',e=>{errors.push(e.message);console.log('RENDERER ERROR',e.message)});await page.waitForFunction(()=>!!window.vm);await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive())}
try{
 await launch()
 if(process.env.VM_TEST_EXECUTABLE){await application.evaluate(({dialog},source)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[source]})},source);const picked=await api('pickRoot');await api('addRoot',picked.grant)}
 const bootstrap=await waitFor(async()=>{const b=await api('bootstrap');return b.roots.length&&b.roots[0].state==='online'&&b.roots[0].lastIndexedAt>0?b:null},'initial scan');const root=bootstrap.roots[0]
 log('Windows 启动、沙箱桥接、目录扫描',{rootState:root.state});assert.equal(await page.evaluate(()=>typeof window.require),'undefined')
 await page.locator('.tree-target').filter({hasText:'影像测试库'}).first().click()
 const direct=await api('openQuery',{...defaultQuery,folderId:root.entryId,scope:'direct'});const page1=await api('page',direct.id,0,100);assert.equal(direct.folders,5);assert.equal(direct.media,21);assert.equal((await api('entry',root.entryId)).other,1);log('直属目录与媒体分区',{folders:direct.folders,media:direct.media})
 const recursive=await api('openQuery',{...defaultQuery,folderId:root.entryId,scope:'descendants'});assert.equal(recursive.folders,0);assert.equal(recursive.media,44);const all=(await api('page',recursive.id,0,100)).entries;assert.equal(new Set(all.map(e=>e.id)).size,44);log('跨层结果去重与来源路径',{media:recursive.media})
 await waitFor(()=>page.locator('.card .thumbnail img').count().then(n=>n>8),'visible thumbnails',60000)
 await api('settings',{theme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await capture('browse-dark')
 const firstCard=page.locator('.viewport [role=option]').first();const selectedName=await firstCard.getAttribute('aria-label');await firstCard.click();await page.getByRole('button',{name:'详细列表',exact:true}).click();await waitFor(()=>page.locator('.list-item[aria-selected=true]').count().then(n=>n===1),'selection preserved');assert.equal(await page.locator('.list-item[aria-selected=true]').getAttribute('aria-label'),selectedName);log('网格／列表插件切换保留选择');await capture('list-dark');await page.getByRole('button',{name:'取消选择 (Esc)'}).click();await page.getByRole('button',{name:'卡片网格',exact:true}).click()
 const picture=all.find(e=>e.name==='西湖 中文图片.png'),video=all.find(e=>e.name==='色彩与节奏.mp4'),folder=page1.entries.find(e=>e.name==='山野与远行');assert(picture&&video&&folder)
 await api('organize',{ids:[picture.id,video.id]},'tag-add','旅行');await api('organize',{ids:[picture.id]},'favorite',true);const search=await api('openQuery',{...defaultQuery,scope:'library',text:'西湖',tags:['旅行'],favorite:true});assert.equal(search.media,1);assert.equal((await api('page',search.id,0,100)).entries[0].id,picture.id);log('短中文搜索、标签与收藏持久化')
 const mediaURL=await api('media',video.id,'original');const range=await page.evaluate(async url=>{const r=await fetch(url,{headers:{Range:'bytes=0-63'}});return {status:r.status,range:r.headers.get('content-range'),length:(await r.arrayBuffer()).byteLength}},mediaURL);assert.equal(range.status,206);assert.equal(range.length,64);log('本地视频 Range 流',{...range})
 const play=await page.evaluate(async url=>{const v=document.createElement('video');v.muted=true;v.src=url;document.body.append(v);try{await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=()=>reject(Error('video load error'))});await v.play();await new Promise(r=>setTimeout(r,1200));const result={duration:v.duration,width:v.videoWidth,time:v.currentTime,readyState:v.readyState,paused:v.paused,error:v.error?.message};v.pause();v.removeAttribute('src');v.load();return result}finally{v.remove()}},mediaURL);console.log('MP4 playback state',play);assert(play.width>0&&play.time>0);log('MP4 H.264 + AAC 内置播放',play)
 const webm=all.find(e=>e.ext==='webm');const webmURL=await api('media',webm.id,'original');const webmInfo=await page.evaluate(async url=>{const v=document.createElement('video');v.muted=true;v.src=url;try{await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=()=>reject(Error('webm load failed'))});await v.play();await new Promise(r=>setTimeout(r,150));return {width:v.videoWidth,duration:v.duration,time:v.currentTime}}finally{v.pause();v.removeAttribute('src');v.load()}},webmURL);assert(webmInfo.time>0);log('WebM VP9 + Opus 内置播放',webmInfo)
 const sourceHandle=await api('coverSource',video.id);const start=performance.now();const frame=await api('frame',sourceHandle.handle,.91,0,1);const latency=performance.now()-start;const next=await api('frame',sourceHandle.handle,frame.time,1,2);assert(next.time>frame.time);const previous=await api('frame',sourceHandle.handle,next.time,-1,3);assert.equal(previous.pts,frame.pts);const target=await api('entry',folder.id);await api('saveCover',folder.id,previous.token,{mode:'contain',x:.5,y:.5,zoom:1},target.coverRevision,'balanced');const afterCover=await api('entry',folder.id);assert.equal(afterCover.coverMode,'manual');const beforeHash=afterCover.coverHash;await api('closeSource',sourceHandle.handle);await api('clearCache');await api('refreshRoot',root.id);await waitFor(async()=>{const b=await api('bootstrap');return b.roots[0].state==='online'},'rescan');assert.equal((await api('entry',folder.id)).coverHash,beforeHash);const thumb=await api('media',folder.id,'thumbnail');assert(thumb.startsWith('media:'));log('真实帧前后步进、封面保存、清缓存与重扫保护',{seekMs:Math.round(latency),pts:frame.pts})
 await page.getByRole('button',{name:'刷新',exact:true}).click();await page.locator('.tree-target').filter({hasText:'影像测试库'}).first().click();await page.waitForTimeout(300);const button=page.getByRole('button',{name:folder.name+' 的更多操作',exact:true}).first();await button.click();await page.getByRole('menuitem',{name:'设置封面',exact:true}).click();await page.getByRole('heading',{name:'设置封面',exact:true}).waitFor();await waitFor(()=>page.locator('.candidates button').count().then(n=>n>0),'cover candidates',60000);await page.locator('.candidates button').first().click();await capture('cover-editor-dark');await page.getByRole('button',{name:'取消',exact:true}).last().click();log('封面编辑器可达并显示候选')
 const rename=await api('plan',{ids:[folder.id]},'rename',null,'山野收藏','keep');assert(rename.items[0].files>0);const task=await api('commit',rename.id);await waitFor(async()=>{const b=await api('bootstrap');return b.tasks.find(t=>t.id===task.id&&!['running','paused'].includes(t.state))},'rename');const renamed=await api('entry',folder.id);assert.equal(renamed.name,'山野收藏');assert.equal(renamed.coverHash,beforeHash);assert((await api('entry',picture.id)).rel.startsWith('山野收藏/'));assert.equal((await api('entry',picture.id)).favorite,1);assert(await fs.stat(path.join(source,'山野收藏')));log('实际目录重命名与后代管理信息保留')
 const destination=page1.entries.find(e=>e.name==='城市漫游');const move=await api('plan',{ids:[video.id]},'move',destination.id,null,'keep');const movedTask=await api('commit',move.id);const movedResult=await waitFor(async()=>{const b=await api('bootstrap');return b.tasks.find(t=>t.id===movedTask.id&&!['running','paused'].includes(t.state))},'move');assert.equal(movedResult.state,'completed');const movedVideo=await api('entry',video.id);assert.equal(movedVideo.parentId,destination.id);assert.deepEqual(movedVideo.tags,['旅行']);log('单文件移动与稳定 ID')
 const trashEntry=all.find(e=>e.name==='portrait.webp');const trashPlan=await api('plan',{ids:[trashEntry.id]},'trash',null,null,'skip');await api('commit',trashPlan.id);const trashed=await waitFor(async()=>{const b=await api('bootstrap');return b.tasks.find(t=>t.id===trashPlan.id&&!['running','paused'].includes(t.state))},'trash');assert.equal(trashed.state,'completed');await assert.rejects(fs.stat(path.join(source,'portrait.webp')));assert.equal((await api('entry',trashEntry.id)).state,'trashed');log('测试文件进入 Windows 系统回收站')
 const archive=path.join(base,'测试媒体库.vmlibrary');await application.evaluate(({dialog},archive)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:archive})},archive);assert.equal(await api('exportLibrary'),archive);assert((await fs.stat(archive)).size>1000);await application.evaluate(({dialog},archive)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[archive]});dialog.showMessageBox=async()=>({response:1,checkboxChecked:false})},archive);const importedId=await api('importLibrary');assert.notEqual(importedId,bootstrap.libraryId);await api('switchLibrary',importedId);const imported=(await api('bootstrap'));assert.equal(imported.roots[0].state,'offline');assert.equal((await api('entry',picture.id)).favorite,1);assert.equal((await api('entry',folder.id)).coverHash,beforeHash);await application.evaluate(({dialog},source)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[source]})},source);const preview=await api('rebindPreview',root.id);assert.equal(preview.conflicts.length,0);await api('rebindRoot',root.id,preview.grant);await waitFor(async()=>{const b=await api('bootstrap');return b.roots[0].state==='online'},'import rebind');log('管理包导出／导入为独立媒体库及根重绑',{matched:preview.matched,total:preview.total,bytes:(await fs.stat(archive)).size})
 await page.locator('.tree-target').filter({hasText:'影像测试库'}).first().click();await api('settings',{theme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await capture('browse-light');await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1280,720));await page.waitForTimeout(400);await capture('browse-1280x720');log('明暗主题及 1280×720 窗口布局')
 await application.close();application=null;await launch();await waitFor(async()=>{const b=await api('bootstrap');return b.roots.length&&b.roots[0].state==='online'},'restart');assert.equal((await api('entry',picture.id)).favorite,1);assert.equal((await api('entry',folder.id)).coverHash,beforeHash);log('应用重启后的组织信息与手动封面持久化')
 assert.deepEqual(errors,[]);log('无渲染进程异常')
}catch(error){console.error(error);results.push({name:'E2E failure',passed:false,error:String(error)});if(page)await capture('failure').catch(()=>{});process.exitCode=1}finally{if(application)await application.close();await fs.writeFile('test-results/e2e-report.json',JSON.stringify({date:new Date().toISOString(),base,results,errors},null,2))}
