import { _electron as electron, chromium } from 'playwright'
import fs from 'node:fs/promises'
import path from 'node:path'
import net from 'node:net'
import assert from 'node:assert/strict'
const executable=process.env.VM_TEST_EXECUTABLE
const label=process.env.VM_UI_LABEL||'development'
const base=path.resolve('.test-data/sharing-'+Date.now()),source=path.join(base,'局域网测试库'),data=path.join(base,'app-data')
await fs.mkdir(base,{recursive:true});await fs.cp(path.resolve('.test-data/fixtures'),source,{recursive:true});await fs.mkdir('test-results',{recursive:true})
const shared=path.join(source,'山野与远行');await fs.copyFile(path.join(source,'色彩与节奏.mp4'),path.join(shared,'共享演示.mp4'))
const files=await fs.readdir(source,{recursive:true});const webm=files.find(name=>name.endsWith('.webm'));assert(webm);await fs.copyFile(path.join(source,webm),path.join(shared,'共享演示.webm'))
const picture=files.find(name=>name.endsWith('.png'));assert(picture);for(let i=0;i<65;i++)await fs.copyFile(path.join(source,picture),path.join(shared,`分页图片 ${String(i).padStart(2,'0')}.png`))
const results=[],errors=[];let application,browser,page,mobile,desktop,status,clipboardBefore
const log=(name,extra={})=>{results.push({name,passed:true,...extra});console.log('PASS',name,JSON.stringify(extra))}
const api=(method,...args)=>page.evaluate(([method,args])=>window.vm[method](...args),[method,args])
async function waitFor(fn,label,timeout=60000){const start=Date.now();while(Date.now()-start<timeout){const result=await fn();if(result)return result;await new Promise(resolve=>setTimeout(resolve,150))}throw Error('Timeout: '+label)}
async function port(){const socket=net.createServer();await new Promise(resolve=>socket.listen(0,'127.0.0.1',resolve));const value=socket.address().port;await new Promise(resolve=>socket.close(resolve));return value}
async function launch(){application=await electron.launch({executablePath:path.resolve(executable||'node_modules/electron/dist/electron.exe'),args:executable?[]:['.'],env:{...process.env,VM_DATA_DIR:data,VM_TEST_HIDDEN:'1'},timeout:30000});page=await application.firstWindow();page.on('pageerror',e=>errors.push('desktop: '+e.message));await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());await page.getByRole('button',{name:'设置与插件',exact:true}).waitFor()}
async function scan(client){await client.goto(status.connectionUrl);await client.locator('#library').waitFor();await client.locator('.media-card').first().waitFor();assert.equal(new URL(client.url()).hash,'');assert.equal(await client.locator('#code').count(),0)}
async function capture(client,name){await client.screenshot({path:`test-results/sharing-${label}-${name}.png`,fullPage:true})}
try{
 await launch();assert.equal((await api('shareStatus')).running,false)
 await application.evaluate(({dialog},source)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[source]})},source);const picked=await api('pickRoot');await api('addRoot',picked.grant)
 const boot=await waitFor(async()=>{const b=await api('bootstrap');return b.roots[0]?.state==='online'&&b.roots[0].lastIndexedAt>0?b:null},'index and thumbnails',120000);const root=boot.roots[0]
 const folders=await api('shareFolders',root.entryId);const allowed=folders.find(e=>e.name==='山野与远行'),hidden=folders.find(e=>e.name==='城市漫游');assert(allowed&&hidden)
 await page.getByRole('button',{name:'设置与插件',exact:true}).click();await page.getByRole('button',{name:'局域网共享',exact:true}).click();await page.getByLabel('共享网络',{exact:true}).selectOption('127.0.0.1');await page.getByLabel('共享端口',{exact:true}).fill(String(await port()));await page.getByLabel('关闭窗口后继续共享',{exact:true}).uncheck();await page.getByRole('button',{name:'展开 局域网测试库',exact:true}).click();await page.getByLabel('共享 山野与远行',{exact:true}).check();await page.getByRole('button',{name:'开启共享',exact:true}).click()
 status=await waitFor(async()=>{const s=await api('shareStatus');return s.running?s:null},'start sharing');assert.deepEqual(status.options.folderIds,[allowed.id]);const invitation=new URLSearchParams(new URL(status.connectionUrl).hash.slice(1)).get('connect');assert.match(invitation,/^[A-Za-z0-9_-]{43}$/);assert.equal(status.code,undefined);assert(status.qr.startsWith('data:image/svg+xml'));await page.waitForFunction(()=>!document.querySelector('.share-busy'));await page.locator('.settings-content').evaluate(e=>e.scrollTop=0);await page.waitForTimeout(200);await capture(page,'desktop-settings');log('桌面选择子目录、网络、端口并显示含授权信息的二维码')
 const bounds=await application.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0],before=w.getBounds();w.setBounds({width:1024,height:768});return before});await api('settings',{theme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await page.waitForTimeout(150);assert.equal(await page.locator('.share-access').evaluate(e=>e.scrollWidth<=e.clientWidth),true);assert.equal(await page.locator('.share-qr img').isVisible(),true);assert.equal(await page.locator('.share-code').count(),0);await capture(page,'desktop-settings-compact-dark');await application.evaluate(({BrowserWindow},before)=>BrowserWindow.getAllWindows()[0].setBounds(before),bounds);await api('settings',{theme:boot.settings.theme??'system'});log('1024 像素共享设置与深色主题，二维码和操作区无横向溢出')
 clipboardBefore=true;await application.evaluate(({clipboard})=>{clipboard.__vmShareCopyOriginal=clipboard.writeText;clipboard.__vmShareCopyValue=null;clipboard.writeText=value=>{clipboard.__vmShareCopyValue=value;clipboard.__vmShareCopyOriginal(value)}});await page.getByRole('button',{name:'复制连接链接',exact:true}).click();await waitFor(()=>application.evaluate(({clipboard},url)=>clipboard.__vmShareCopyValue===url,status.connectionUrl),'connection link IPC payload');await application.evaluate(({clipboard})=>{clipboard.writeText=clipboard.__vmShareCopyOriginal;delete clipboard.__vmShareCopyOriginal;delete clipboard.__vmShareCopyValue});clipboardBefore=undefined;log('复制连接链接通过受验证桌面接口提交完整扫码授权链接',{scope:'验证 UI、IPC 及原生写入调用；当前测试进程不能从系统剪贴板读回文本'})
 browser=await chromium.launch({channel:process.env.VM_BROWSER_CHANNEL||'chrome',headless:true});const phone=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});mobile=await phone.newPage();mobile.on('pageerror',e=>errors.push('browser: '+e.message));await mobile.goto(status.url);await mobile.locator('#pair-error').filter({hasText:'仅打开共享网址'}).waitFor();await capture(mobile,'mobile-connect');assert.equal(await mobile.locator('#library').isVisible(),false);assert.equal(await mobile.locator('#code').count(),0);const denied=await mobile.request.get(status.url+'/api/browse');assert.equal(denied.status(),401);assert.equal((await mobile.request.get(status.url+'/api/session')).status(),401);log('普通共享网址只显示扫码提示，不授予媒体访问权限')
 await mobile.goto(status.url+'/?connect='+invitation);await mobile.locator('#pair-error').filter({hasText:'仅打开共享网址'}).waitFor();assert.equal((await mobile.request.get(status.url+'/api/browse')).status(),401);await mobile.goto(status.url+'/#connect=invalid');await mobile.locator('#pair-error').filter({hasText:'二维码无效或已过期'}).waitFor();assert.equal(new URL(mobile.url()).hash,'');assert.equal((await mobile.request.get(status.url+'/api/browse')).status(),401);log('查询参数与无效扫码凭证不能绕过授权，错误页面清理凭证片段')
 const requestUrls=[];mobile.on('request',request=>requestUrls.push(request.url()));await scan(mobile);assert(requestUrls.every(url=>!url.includes(invitation)));assert.equal(await mobile.evaluate(secret=>JSON.stringify(localStorage).includes(secret),invitation),false);const phoneSession=await (await mobile.request.get(status.url+'/api/session')).json();const originalCookie=(await phone.cookies()).find(c=>c.name==='vm_lan_session');assert(originalCookie&&originalCookie.value!==invitation);assert.equal(await mobile.evaluate(()=>typeof window.vm),'undefined');assert.equal(await mobile.locator('.media-card').count(),1);log('扫码链接自动授权，地址栏、资源请求与本地存储不保留二维码凭证')
 await mobile.reload();await mobile.locator('.media-card').first().waitFor();assert.equal((await api('shareStatus')).devices.length,1);await scan(mobile);assert.equal((await api('shareStatus')).devices.length,1);assert.equal((await (await mobile.request.get(status.url+'/api/session')).json()).deviceId,phoneSession.deviceId);log('刷新页面与重复扫码复用授权，不增加设备名额')
 await mobile.getByRole('button',{name:'山野与远行',exact:true}).click();await mobile.locator('.media-card').first().waitFor();await mobile.screenshot({path:`test-results/sharing-${label}-mobile-library.png`});assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);log('393 像素手机布局、自动连接后目录浏览、无横向溢出')
 const list=await mobile.request.get(status.url+'/api/browse?text=共享演示');const entries=(await list.json()).entries;const video=entries.find(e=>e.ext==='mp4'),vp9=entries.find(e=>e.ext==='webm');assert(video&&vp9);assert.equal((await mobile.request.get(status.url+'/api/browse?folderId='+hidden.id)).status(),404);const query=await api('openQuery',{folderId:root.entryId,scope:'direct'});const local=(await api('page',query.id,0,100)).entries;const privateVideo=local.find(e=>e.name==='色彩与节奏.mp4');assert(privateVideo);assert.equal((await mobile.request.get(status.url+'/api/media/'+privateVideo.id+'/original')).status(),404);assert.equal((await mobile.request.get(status.url+'/api/media/'+privateVideo.id+'/thumbnail')).status(),404);const remote=JSON.stringify(await (await mobile.request.get(status.url+'/api/browse?text=色彩')).json());assert(!remote.includes('色彩与节奏'));assert(!JSON.stringify(await list.json()).includes('rootId'));log('目录、搜索、原文件、封面共同限制共享范围，返回数据隐藏路径')
 await mobile.locator('#more').click();await waitFor(()=>mobile.locator('.media-card').count().then(n=>n>60),'pagination');log('分页追加、中文文件名与懒加载封面',{visible:await mobile.locator('.media-card').count()})
 await mobile.locator('#search').fill('共享演示');await waitFor(()=>mobile.locator('.media-card').count().then(n=>n===2),'search');await mobile.getByRole('button',{name:'共享演示.mp4',exact:true}).click();await mobile.waitForFunction(()=>{const v=document.querySelector('video');return v?.videoWidth>0&&v.currentTime>0},{},{timeout:30000});await mobile.evaluate(()=>{const v=document.querySelector('video');v.currentTime=1;v.pause()});await waitFor(()=>mobile.evaluate(()=>JSON.stringify(localStorage).includes('vm-lan-progress')),'saved progress');assert.equal((await api('entry',video.id)).playback,0);await capture(mobile,'mobile-player');const actualPlay=await mobile.evaluate(()=>{const v=document.querySelector('video');return {width:v.videoWidth,duration:v.duration,position:v.currentTime}});await mobile.getByRole('button',{name:'关闭查看器',exact:true}).click();await mobile.getByRole('button',{name:'共享演示.mp4',exact:true}).click();await mobile.waitForFunction(()=>document.querySelector('video')?.currentTime>=.9);log('HTTP MP4 真实解码、拖动、独立续播且不覆盖桌面进度',actualPlay)
 await mobile.getByRole('button',{name:'关闭查看器',exact:true}).click();const originalUrl=status.url+'/api/media/'+video.id+'/original';await mobile.route(originalUrl,route=>route.abort());await mobile.getByRole('button',{name:'共享演示.mp4',exact:true}).click();await mobile.locator('#viewer-error').waitFor();await mobile.getByRole('button',{name:'关闭查看器',exact:true}).click();const retainedProgress=await mobile.evaluate(id=>{const key=Object.keys(localStorage).find(key=>key.includes(id));return JSON.parse(localStorage.getItem(key)).position},video.id);assert(retainedProgress>=.9);await mobile.unroute(originalUrl);await mobile.getByRole('button',{name:'共享演示.mp4',exact:true}).click();await mobile.waitForFunction(()=>document.querySelector('video')?.currentTime>=.9);log('视频加载失败保留续播位置，连接恢复后继续播放')
 const range=await mobile.request.get(status.url+'/api/media/'+video.id+'/original',{headers:{Range:'bytes=64-127'}});assert.equal(range.status(),206);assert.equal((await range.body()).length,64);assert(range.headers()['content-range'].startsWith('bytes 64-127/'));const head=await mobile.request.head(status.url+'/api/media/'+video.id+'/original');assert.equal(head.status(),200);assert.equal((await mobile.request.get(status.url+'/api/media/'+video.id+'/original',{headers:{Range:'bytes=999999999-'}})).status(),416);log('206 分段、HEAD 与 416 越界范围')
 await mobile.getByRole('button',{name:'关闭查看器',exact:true}).click();await mobile.getByRole('button',{name:'共享演示.webm',exact:true}).click();await mobile.waitForFunction(()=>document.querySelector('video')?.currentTime>0);log('HTTP WebM VP9 + Opus 真实解码');await mobile.getByRole('button',{name:'关闭查看器',exact:true}).click()
 await mobile.locator('#search').fill('分页图片 00');await waitFor(()=>mobile.locator('.media-card').count().then(n=>n===1),'image search');await mobile.getByRole('button',{name:'分页图片 00.png',exact:true}).click();await mobile.waitForFunction(()=>document.querySelector('#viewer-stage img')?.naturalWidth>0);await mobile.locator('#viewer-stage img').click();assert(await mobile.locator('#viewer-stage img').evaluate(e=>e.classList.contains('zoomed')));await mobile.getByRole('button',{name:'全屏',exact:true}).click();await mobile.waitForFunction(()=>!!document.fullscreenElement);await mobile.evaluate(()=>document.exitFullscreen());await mobile.getByRole('button',{name:'关闭查看器',exact:true}).click();await mobile.locator('#search').fill('共享演示');await waitFor(()=>mobile.locator('.media-card').count().then(n=>n===2),'return to video search');log('图片原文件预览、缩放和浏览器全屏')
 const second=await browser.newContext({viewport:{width:1280,height:900}});desktop=await second.newPage();desktop.on('pageerror',e=>errors.push('second browser: '+e.message));await scan(desktop);await desktop.getByRole('button',{name:'山野与远行',exact:true}).click();await desktop.locator('#search').fill('共享演示');await waitFor(()=>desktop.locator('.media-card').count().then(n=>n===2),'second search');await desktop.getByRole('button',{name:'共享演示.mp4',exact:true}).click();await desktop.waitForFunction(()=>document.querySelector('video')?.currentTime>0);await desktop.getByRole('button',{name:'关闭查看器',exact:true}).click();await desktop.getByRole('button',{name:'切换明暗主题',exact:true}).click();await capture(desktop,'desktop-browser');assert.equal((await api('shareStatus')).devices.length,2);const cookies=await second.cookies();assert(cookies.find(c=>c.name==='vm_lan_session').httpOnly);assert.equal(await desktop.evaluate(()=>document.cookie.includes('vm_lan_session')),false);log('第二浏览器独立设备、真实播放、明暗主题与 HttpOnly 授权')
 const oldConnection=status.connectionUrl;await page.getByRole('button',{name:'刷新二维码',exact:true}).click();status=await waitFor(async()=>{const s=await api('shareStatus');return s.connectionUrl!==oldConnection?s:null},'renew QR');assert.equal((await desktop.request.get(status.url+'/api/session')).status(),200);const visitor=await browser.newContext({viewport:{width:393,height:852}});const guest=await visitor.newPage();guest.on('pageerror',e=>errors.push('guest browser: '+e.message));await guest.goto(oldConnection);await guest.locator('#pair-error').filter({hasText:'二维码无效或已过期'}).waitFor();assert.equal((await guest.request.get(status.url+'/api/browse')).status(),401);await visitor.close();log('桌面刷新二维码使旧链接失效，已有设备继续访问')
 await mobile.getByRole('button',{name:'共享演示.mp4',exact:true}).click();const connected=await api('shareStatus');const phoneDevice=connected.devices.find(d=>d.id===phoneSession.deviceId);assert(phoneDevice);const beforeRevoke=status.connectionUrl;status=await api('shareRevoke',phoneDevice.id);assert.notEqual(status.connectionUrl,beforeRevoke);assert.equal((await mobile.request.get(status.url+'/api/session')).status(),401);assert.equal((await desktop.request.get(status.url+'/api/session')).status(),200);await mobile.goto(beforeRevoke);await mobile.locator('#pair-error').filter({hasText:'二维码无效或已过期'}).waitFor();assert.equal((await mobile.request.get(status.url+'/api/browse')).status(),401);log('撤销设备中断访问并轮换二维码，原扫码链接不能重新授权')
 await scan(mobile);assert.equal((await api('shareStatus')).devices.length,2);await mobile.getByRole('button',{name:'退出设备',exact:true}).click();await mobile.locator('#pair-error').filter({hasText:'此设备已退出'}).waitFor();assert.equal((await mobile.request.get(status.url+'/api/browse')).status(),401);assert.equal((await api('shareStatus')).devices.length,1);log('新二维码重新授权，主动退出清除会话并释放设备名额')
 await api('shareStop');await assert.rejects(desktop.request.get(status.url+'/api/session',{timeout:3000}));const beforeRestart=await api('bootstrap');assert.deepEqual(beforeRestart.settings.lanSharing.folderIds,[allowed.id]);await application.close();application=null;await launch();assert.equal((await api('shareStatus')).running,false);log('停止服务关闭端口，配置持久化，重启默认关闭')
 const config=beforeRestart.settings.lanSharing;status=await api('shareStart',{...config,port:await port(),keepInTray:true});await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),false);assert.equal((await api('shareStatus')).running,true);await api('shareStop');assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),true);log('关闭窗口留在托盘继续共享，停止后恢复窗口')
 const lan=(await api('shareStatus')).interfaces.find(i=>!i.loopback);if(lan){status=await api('shareStart',{...config,host:lan.address,port:await port(),keepInTray:false});const actual=await fetch(status.url);assert.equal(actual.status,200);await api('shareStop');log('实际局域网 IPv4 网卡监听及地址访问',{address:lan.address})}
 const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');const measure=async()=>{const before=(await cdp.send('Performance.getMetrics')).metrics;await page.waitForTimeout(2000);const after=(await cdp.send('Performance.getMetrics')).metrics;const delta=name=>+((after.find(m=>m.name===name).value-before.find(m=>m.name===name).value)*1000).toFixed(2);return {taskMs:delta('TaskDuration'),styleMs:delta('RecalcStyleDuration'),layoutMs:delta('LayoutDuration'),animations:await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length)}};const shareOff=await measure();
 const retained=await api('bootstrap');status=await api('shareStart',{...config,host:'127.0.0.1',port:await port(),keepInTray:false});await page.waitForTimeout(200);const shareOn=await measure();assert.equal(shareOn.animations,0);log('同一桌面空闲视图的共享开启前后渲染采样',{scope:'2 秒主线程采样，不包含服务进程、GPU、Wi-Fi 或高码率负载',off:shareOff,on:shareOn});const transfer=path.join(base,'切换测试.vmlibrary');await application.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});dialog.showMessageBox=async()=>({response:1,checkboxChecked:false})},transfer);await api('exportLibrary');const imported=await api('importLibrary');assert.notEqual(imported,retained.libraryId);await api('switchLibrary',imported);assert.equal((await api('shareStatus')).running,false);await assert.rejects(fetch(status.url));log('切换媒体库关闭监听并撤销原共享会话')
 assert.deepEqual(errors,[]);log('桌面及两种浏览器页面无未处理异常')
}catch(error){console.error(error);results.push({name:'共享端到端回归失败',passed:false,error:String(error)});process.exitCode=1;if(mobile)await capture(mobile,'failure-mobile').catch(()=>{});if(page)await capture(page,'failure-desktop').catch(()=>{})}
finally{if(browser)await browser.close();if(application){if(clipboardBefore)await application.evaluate(({clipboard})=>{if(clipboard.__vmShareCopyOriginal)clipboard.writeText=clipboard.__vmShareCopyOriginal;delete clipboard.__vmShareCopyOriginal;delete clipboard.__vmShareCopyValue}).catch(()=>{});await api('shareStop').catch(()=>{});await application.close()}await fs.writeFile(`test-results/sharing-${label}-report.json`,JSON.stringify({date:new Date().toISOString(),base,scope:'隔离媒体样本；真实 Windows Electron 与 Chrome，手机为浏览器触屏视口模拟；无物理手机、跨机器或 Wi-Fi 带宽验收。',results,errors},null,2))}
