import {coverQualities,defaultCoverQuality,type CoverQuality} from '../../../../packages/contracts/covers'
import { app,BrowserWindow,protocol,session,ipcMain,dialog,shell,clipboard,nativeTheme,utilityProcess,Tray,Menu } from 'electron'
import fs from 'node:fs/promises'
import { createReadStream } from 'node:fs'
import path from 'node:path'
import { fileURLToPath,pathToFileURL } from 'node:url'
import { randomUUID } from 'node:crypto'
import { Readable } from 'node:stream'
import { WorkerClient } from './worker'
import { NativeClient } from '../../../../packages/platform/native'
import { PluginManager } from '../../../../packages/cordis-adapter'
import { MpvPlayer } from './mpv'
import { MediaService } from './media'
import { LanSharing } from './sharing'
import { OperationService } from './operations'
import { ScrapeService } from './scrape'
import { providers as scrapeProviders } from './scrape/providers'
import { setProxyResolver,parseSystemProxy } from './scrape/proxy'
import { exportArchive,inspectArchive } from './archive'
import { ipcSchemas, type MpvBounds,type Root,type Task,type Entry, type VMEvent, type Selection } from '../../../../packages/contracts'
import { parseRange } from '../../../../packages/domain'
import { fingerprint } from '../../../../packages/platform/fingerprint'
import { logFailure } from './diagnostics'

const here=path.dirname(fileURLToPath(import.meta.url))
app.setName('VideoManager')
app.setAppUserModelId('local.videomanager.desktop')
const nativeDir=app.isPackaged?path.join(process.resourcesPath,'native'):path.resolve(here,'../../native/bin')
const userData=process.env.VM_DATA_DIR?path.resolve(process.env.VM_DATA_DIR):app.getPath('userData')
app.setPath('userData',userData)
protocol.registerSchemesAsPrivileged([{scheme:'app',privileges:{standard:true,secure:true,supportFetchAPI:true}},{scheme:'media',privileges:{standard:true,secure:true,supportFetchAPI:true,stream:true,corsEnabled:true}}])
const single=app.requestSingleInstanceLock();if(!single)app.quit()
let window:BrowserWindow|null=null;let db:WorkerClient;let reader:WorkerClient;let images:WorkerClient;let indexer:Electron.UtilityProcess;let media:MediaService;let mpv:MpvPlayer;let operations:OperationService;let scrape:ScrapeService;let plugins:PluginManager;let nativeFs:NativeClient
let dataDir='';let libraryId='';let catalog:{current:string;libraries:{id:string;name:string;originId?:string}[]};let closing=false;let sequence=0;let scanPaused=false;let indexConcurrency=4;let coverConcurrency=2
const tasks=new Map<string,Task>();const rootScans=new Map<string,string>();const scheduleTimers=new Map<string,ReturnType<typeof setInterval>>();const coverControls=new Map<string,{pause:boolean;cancel:boolean}>();const grants=new Map<string,{path:string;rootId?:string;matches?:any[];identity?:string}>()
let changeTimer:ReturnType<typeof setTimeout>|null=null
let sharing:LanSharing;let tray:Tray|null=null
function ensureTray(){if(tray)return;tray=new Tray(app.isPackaged?path.join(process.resourcesPath,'icon.ico'):path.resolve('build/icon.ico'));tray.setToolTip('VideoManager · 局域网共享');const show=()=>{window?.show();window?.focus()};tray.on('double-click',show);tray.setContextMenu(Menu.buildFromTemplate([{label:'打开 VideoManager',click:show},{type:'separator'},{label:'停止共享并退出',click:()=>app.quit()}]))}
function send(topic:string,data?:unknown){if(!window||window.isDestroyed())return;const event:VMEvent={topic,sequence:++sequence,...(data!==undefined?{data}:{})};window.webContents.send('vm:event',event)}
function syncWindowTheme(){if(!window||window.isDestroyed())return;const dark=nativeTheme.shouldUseDarkColors;window.setTitleBarOverlay({color:dark?'#0f141a':'#f4f7f9',symbolColor:dark?'#f1f5f9':'#152231'});window.setBackgroundColor(dark?'#0f141a':'#f4f7f9')}
nativeTheme.on('updated',syncWindowTheme)
function changed(){if(changeTimer)return;changeTimer=setTimeout(()=>{changeTimer=null;send('changed')},250)}
function progress(task:Task){tasks.set(task.id,task);if(tasks.size>100){const done=[...tasks].find(([,t])=>!['running','paused'].includes(t.state));if(done)tasks.delete(done[0])}send('task',task);if(task.kind==='scan'&&!['running','paused'].includes(task.state)){media?.resetFailures();coverControls.delete(task.id);for(const [id,taskId]of rootScans)if(taskId===task.id)rootScans.delete(id);changed()}}
function scheduleRoot(root:Root){const prior=scheduleTimers.get(root.id);if(prior)clearInterval(prior);scheduleTimers.delete(root.id);if(root.indexMode==='scheduled'&&root.path){const timer=setInterval(()=>scanRoot(root),Math.max(1,root.intervalMinutes)*60_000);timer.unref();scheduleTimers.set(root.id,timer)}}
async function activateRoots(){for(const root of await db.call<Root[]>('roots')){let state='offline';if(root.path)try{const stat=await nativeFs.call('stat',{path:root.path});state=stat.identity===root.identity?'online':'mismatch'}catch{state='offline'}await db.call('rootState',root.id,state);scheduleRoot({...root,state})}}
async function createIndexCovers(rootId:string,generation:string,initial:Task){const control={pause:false,cancel:false};coverControls.set(initial.id,control);const task:Task={...initial,state:'running',phase:'covers',coversProcessed:0,coversTotal:0,message:'正在准备封面队列'};let last=0;const emit=(force=false)=>{if(force||Date.now()-last>160){last=Date.now();progress({...task})}};try{const entries=await db.call<Entry[]>('indexEntries',rootId,generation);task.coversTotal=entries.length;task.total=task.processed+entries.length;task.progress=task.total?Math.round(task.processed/task.total*100):99;task.message=entries.length?'正在创建缩略图与目录封面':'正在完成索引';emit(true);const run=async(items:Entry[],concurrency:number)=>{let cursor=0;const worker=async()=>{while(cursor<items.length){while(control.pause&&!control.cancel){task.state='paused';emit();await new Promise(resolve=>setTimeout(resolve,150))}if(control.cancel)throw Error('CANCELLED');task.state='running';const entry=items[cursor++]!;task.message=`创建封面 · ${entry.name}`;try{await media.indexThumbnail(entry)}catch{task.failed++}task.coversProcessed=(task.coversProcessed??0)+1;task.processed++;task.progress=task.total?Math.min(99,Math.round(task.processed/task.total*100)):99;emit()}};await Promise.all(Array.from({length:Math.min(concurrency,Math.max(1,items.length))},worker))};const mediaEntries=entries.filter(entry=>entry.kind!=='folder');const folders=entries.filter(entry=>entry.kind==='folder');await run(mediaEntries,coverConcurrency);for(const depth of [...new Set(folders.map(entry=>(entry.rel?entry.rel.split('/').length:0)))].sort((a,b)=>b-a))await run(folders.filter(entry=>(entry.rel?entry.rel.split('/').length:0)===depth),coverConcurrency);task.phase='finalizing';task.progress=99;task.message='正在提交索引结果';emit(true);await db.call('rootIndexed',rootId);task.progress=100;task.processed=task.total??task.processed;task.state=task.failed?'completed-errors':'completed';task.message=task.failed?`索引已完成，${task.failed} 个文件或封面处理失败`:'索引和封面已全部建立';emit(true)}catch(error){task.state=control.cancel?'cancelled':'failed';task.message=control.cancel?'已取消封面创建；文件目录索引已保留':String(error);await db.call('rootState',rootId,control.cancel?'incomplete':'offline');emit(true)}}
async function writeCatalog(){await fs.mkdir(userData,{recursive:true});const file=path.join(userData,'catalog.json');await fs.writeFile(file+'.tmp',JSON.stringify(catalog));await fs.rename(file+'.tmp',file)}
async function initLibrary(id:string){
 libraryId=id;dataDir=path.join(userData,'libraries',id);await Promise.all(['temp','cache','objects'].map(d=>fs.mkdir(path.join(dataDir,d),{recursive:true})))
 db=new WorkerClient(path.join(here,'database.cjs'),'数据库写入');await db.call('init',path.join(dataDir,'library.sqlite'),false)
 reader=new WorkerClient(path.join(here,'database.cjs'),'查询');await reader.call('init',path.join(dataDir,'library.sqlite'),true)
 images=new WorkerClient(path.join(here,'images.cjs'),'图像处理');nativeFs=new NativeClient(path.join(nativeDir,'vm-fs.exe'))
 mpv=new MpvPlayer(path.join(nativeDir,'mpv','mpv.exe'),(id,position,revision)=>db.call('playback',id,position,revision),state=>send('mpv-state',state),action=>send('mpv-action',action))
 media=new MediaService(dataDir,nativeDir,db,images,nativeFs,changed);operations=new OperationService(db,nativeFs,media,progress,quiesce,()=>{scanPaused=false;void refreshAll();changed()})
 sharing=new LanSharing(here,path.join(dataDir,'library.sqlite'),reader,media,id,options=>db.call('settings',{lanSharing:options}),()=>send('sharing-changed'))
 scrape=new ScrapeService(dataDir,db,media,progress,changed,entry=>send('entry-changed',entry))
 // 刮削请求自动使用系统代理（支持 PAC 按域名分流）；Node fetch 默认不走系统代理。
 setProxyResolver(url=>session.defaultSession.resolveProxy(url))
 void session.defaultSession.resolveProxy('https://www.javbus.com/').then(async hint=>{
   const proxy=parseSystemProxy(hint);await scrape.logEvent('proxy-detected','javbus.com',proxy??'DIRECT')
 }).catch(()=>{})
 plugins=new PluginManager();const settings=await db.call('settings');indexConcurrency=Math.min(16,Math.max(1,Math.round(Number(settings.indexConcurrency??4))));coverConcurrency=Math.min(16,Math.max(1,Math.round(Number(settings.coverConcurrency??2))));media.thumbnailConcurrency=coverConcurrency;media.coverQuality=(settings.coverQuality??defaultCoverQuality) as CoverQuality;await plugins.init(settings.plugins??{});media.autoEnabled=plugins.enabled('cover-local');await operations.recover();await media.cleanupStorage()
 indexer=utilityProcess.fork(path.join(here,'indexer.cjs'),[],{serviceName:'VideoManager 目录索引',stdio:'pipe'});indexer.on('message',async message=>{if(message.rpc){try{indexer.postMessage({rpc:message.rpc,result:await db.call(message.method,...message.args)})}catch(error){indexer.postMessage({rpc:message.rpc,error:String(error)})}}else if(message.event==='task')progress(message.task);else if(message.event==='catalogued')void createIndexCovers(message.rootId,message.generation,message.task);else if(message.event==='changed')changed()});indexer.on('exit',()=>{for(const [id,taskId]of rootScans){if(!coverControls.has(taskId)){progress({id:taskId,kind:'scan',name:'索引中断',state:'failed',discovered:0,processed:0,failed:1,message:'索引服务退出，请重新启动应用'});void db.call('rootState',id,'incomplete')}}});indexer.postMessage({method:'init',native:path.join(nativeDir,'vm-fs.exe')})
 await activateRoots();nativeTheme.themeSource=['dark','light','system'].includes(settings.theme)?settings.theme:'system';syncWindowTheme()
}
async function quiesce(){await mpv?.closeAll();scanPaused=true;for(const id of rootScans.values())indexer.postMessage({method:'control',id,action:'cancel'});for(const control of coverControls.values())control.cancel=true;const start=Date.now();while(rootScans.size){if(Date.now()-start>30000)throw Error('扫描尚未到达安全停止点，请稍后重试');await new Promise(resolve=>setTimeout(resolve,100))}}
async function refreshAll(){for(const root of await db.call<Root[]>('roots')){if(root.path)scanRoot(root)}}
function scanRoot(root:Root){if(scanPaused||rootScans.has(root.id))return;const taskId=`scan-${root.id}`;rootScans.set(root.id,taskId);progress({id:taskId,kind:'scan',name:'索引 '+root.name,state:'running',discovered:0,processed:0,total:0,failed:0,message:'准备统计待处理文件',phase:'discover',progress:0});indexer.postMessage({method:'scan',root,taskId,excluded:[userData],concurrency:indexConcurrency})}
async function disposeLibrary(){await sharing?.stop();tray?.destroy();tray=null;scrape?.cancelAll();await quiesce();for(const timer of scheduleTimers.values())clearInterval(timer);scheduleTimers.clear();coverControls.clear();await mpv.dispose();media.close();indexer?.kill();images.close();reader.close();db.close();nativeFs.close();await plugins.close();tasks.clear();grants.clear();scanPaused=false}
async function absoluteEntry(id:string){const e=await db.call<Entry>('entry',id);return {e,file:await media.sourcePath(e)}}
const common={
 async shareStatus(){return sharing.status()},
 async shareCopyConnection(){const status=await sharing.status();if(!status.running)throw Error('请先开启共享');if(status.qrExpires<=Date.now())throw Error('二维码已过期，请先刷新二维码');clipboard.writeText(status.connectionUrl)},
 async shareStart(options:import('../../../../packages/contracts/sharing').ShareOptions){const status=await sharing.start(options);if(options.keepInTray)ensureTray();return status},
 async shareStop(){const status=await sharing.stop();tray?.destroy();tray=null;window?.show();return status},
 async shareRevoke(id:string){return sharing.revoke(id)},async shareRenewQr(){return sharing.renew()},
 async shareFolders(id:string){return (await reader.call<Entry[]>('children',id)).map(({id,name})=>({id,name}))},
 async bootstrap(){const info=await db.call('info');return {...info,libraryId,libraries:catalog.libraries,plugins:plugins.list(),tasks:[...tasks.values()],version:app.getVersion()}},
 async pickRoot(){const result=await dialog.showOpenDialog(window!,{title:'添加资源目录',properties:['openDirectory','dontAddToRecent']});if(result.canceled||!result.filePaths[0])return null;const full=await fs.realpath(result.filePaths[0]);const stat=await nativeFs.call('stat',{path:full});if(!stat.directory||stat.reparse)throw Error('请选择实际文件夹');const roots=await db.call<Root[]>('roots');const grant=randomUUID();grants.set(grant,{path:full});return {grant,path:full,overlaps:roots.filter(r=>r.path&&r.path.toLowerCase().startsWith(full.toLowerCase()+path.sep)).map(r=>r.name)}},
 async addRoot(grant:string){const selected=grants.get(grant);if(!selected)throw Error('目录授权已过期，请重新选择');const full=selected.path;const roots=await db.call<Root[]>('allRoots');const parent=roots.find(r=>r.active&&r.path&&(full.toLowerCase()===r.path.toLowerCase()||full.toLowerCase().startsWith(r.path.toLowerCase()+path.sep)));if(parent){scanRoot(parent);return parent}
  const stat=await nativeFs.call('stat',{path:full});const merges=roots.filter(r=>r.active&&r.path&&r.path.toLowerCase().startsWith(full.toLowerCase()+path.sep)).map(r=>({id:r.id,prefix:path.relative(full,r.path).split(path.sep).join('/')}));if(merges.length)await quiesce();const root=await db.call<Root>('addRoot',{id:randomUUID(),name:path.basename(full)||full,path:full,entryId:randomUUID(),identity:stat.identity},merges);for(const merge of merges){const timer=scheduleTimers.get(merge.id);if(timer)clearInterval(timer);scheduleTimers.delete(merge.id)}scanPaused=false;grants.delete(grant);scheduleRoot(root);scanRoot(root);changed();return root},
 async removeRoot(id:string){await sharing.stop();await quiesce();await db.call('archiveRoot',id);const timer=scheduleTimers.get(id);if(timer)clearInterval(timer);scheduleTimers.delete(id);scanPaused=false;changed()},
 async refreshRoot(id:string){const root=await db.call<Root>('root',id);scanRoot(root)},
 async setRootIndexing(id:string,mode:'manual'|'scheduled',intervalMinutes:number){const root=await db.call<Root>('rootIndexing',id,mode,intervalMinutes);scheduleRoot(root);changed();return root},
 async rebindPreview(id:string){const result=await dialog.showOpenDialog(window!,{title:'选择资源根目录的新位置',properties:['openDirectory']});if(result.canceled||!result.filePaths[0])return null;const full=await fs.realpath(result.filePaths[0]);const rootStat=await nativeFs.call('stat',{path:full});const roots=await db.call<Root[]>('roots');if(roots.some(r=>r.id!==id&&r.path&&(full.toLowerCase()===r.path.toLowerCase()||full.toLowerCase().startsWith(r.path.toLowerCase()+path.sep)||r.path.toLowerCase().startsWith(full.toLowerCase()+path.sep))))throw Error('新位置与现有资源根目录重叠');const entries=await db.call<any[]>('rootEntries',id);const matches:any[]=[];const conflicts:string[]=[]
  for(const e of entries){try{const file=path.join(full,...e.rel.split('/'));const stat=await nativeFs.call('stat',{path:file});if(stat.reparse||stat.directory!==(e.kind==='folder'))throw Error('类型不匹配');if(e.kind!=='folder'&&stat.identity!==e.identity&&(!e.fingerprint||stat.size!==e.size||await fingerprint(file)!==e.fingerprint))throw Error('身份或内容证据不足');matches.push({id:e.id,identity:stat.identity})}catch{conflicts.push(e.rel||'根目录')}}
  const grant=randomUUID();grants.set(grant,{path:full,rootId:id,matches,identity:rootStat.identity});return {grant,total:entries.length,matched:matches.length,conflicts:conflicts.slice(0,100),path:full}},
 async rebindRoot(id:string,grant:string){await sharing.stop();const selected=grants.get(grant);if(!selected||selected.rootId!==id)throw Error('重绑预览已过期');await quiesce();await db.call('rebind',id,selected.path,selected.identity,selected.matches);grants.delete(grant);scanPaused=false;const root=await db.call<Root>('root',id);scheduleRoot(root);scanRoot(root);changed()},
 async openQuery(spec:any){const result=await reader.call('openQuery',spec);return {...result,complete:result.complete&&!rootScans.size}}, async page(id:string,offset:number,limit=100){return reader.call('page',id,offset,limit)}, async position(id:string,entryId:string){return reader.call('position',id,entryId)},async entry(id:string){return reader.call('entry',id)},async ancestors(id:string){return reader.call('ancestors',id)},async children(id:string){return reader.call('children',id)},
 async freeze(id:string){if(rootScans.size)throw Error('索引未完成，暂不能全选所有结果');const rows=await reader.call('sessionIds',id);return db.call('freeze',rows)},
 async organize(selection:Selection,action:string,value:string|boolean){if(!plugins.enabled('organization'))throw Error('请先启用标签与收藏插件');await db.call('organize',selection,action,value);changed()},
 async media(id:string,purpose:string){if(purpose==='thumbnail'&&!plugins.enabled('cover-local')){const e=await db.call<Entry>('entry',id);if(e.kind!=='image'&&!e.coverHash)throw Error('自动封面插件已停用')}return media.media(id,purpose)},async release(url:string){media.release(url)},async playback(id:string,position:number){const lease=[...media.leases.values()].find(lease=>lease.entryId===id);if(lease)await db.call('playback',id,position,lease.revision)},
 async mpvBounds(sessionId:string,bounds:MpvBounds){await mpv.bounds(sessionId,bounds)},
 async startMpv(id:string,bounds:MpvBounds){if(!plugins.enabled('viewer-mpv'))throw Error('请先选择 mpv 播放器');const {e,file}=await absoluteEntry(id);if(e.kind!=='video')throw Error('请选择视频文件');if(!window||window.isDestroyed())throw Error('播放窗口不可用');return mpv.open(e,file,window.getNativeWindowHandle().readUInt32LE(0),bounds)},
 async mpvControl(sessionId:string,action:import('../../../../packages/contracts').MpvAction,value?:number){await mpv.control(sessionId,action,value)},async closeMpv(sessionId:string){await mpv.close(sessionId)},
 async system(id:string,action:string){const {file}=await absoluteEntry(id);if(action==='copy')clipboard.writeText(file);else if(action==='reveal')shell.showItemInFolder(file);else{const error=await shell.openPath(file);if(error)throw Error(error)}},
 async coverSource(id:string|null){return media.source(id)},async coverSnapshot(id:string){return media.coverSnapshot(id)},async frame(handle:string,time:number,step:number,generation:number){return media.frame(handle,time,step,generation)},async closeSource(handle:string){media.closeSource(handle)},async saveCover(target:string,token:string,crop:any,revision:number,quality:'compact'|'original'|'high'|'balanced'|'fast'){await media.save(target,token,crop,revision,quality);const entry=await db.call<Entry>('entry',target);send('entry-changed',entry);for(const ancestor of await media.refreshAncestorCovers(target))send('entry-changed',ancestor);return entry},async recommend(target:string){return media.recommend(target)},async restoreCover(target:string,revision:number){await media.restore(target,revision);const entry=await db.call<Entry>('entry',target);send('entry-changed',entry);for(const ancestor of await media.refreshAncestorCovers(target))send('entry-changed',ancestor);return entry},
 async plan(...args:Parameters<OperationService['plan']>){if(!plugins.enabled('file-actions'))throw Error('请先启用文件管理插件');return operations.plan(...args)},
 async commit(id:string){return operations.commit(id)},
 async taskAction(id:string,action:string){const task=tasks.get(id);const cover=coverControls.get(id);if(cover){if(action==='pause')cover.pause=true;if(action==='resume')cover.pause=false;if(action==='cancel')cover.cancel=true}else if(task?.kind==='scan')indexer.postMessage({method:'control',id,action});else if(task?.kind==='scrape')scrape.cancel(id);else if(action==='cancel')operations.cancel(id)},async plugins(){return plugins.list()},
 async setPlugin(id:string,enabled:boolean,config:Record<string,unknown>){if(['builtin.viewer-video','builtin.viewer-mpv','builtin.viewer-system'].includes(id))await mpv.closeAll();if(operations.busy&&id==='builtin.file-actions'&&!enabled)throw Error('文件操作正在安全提交，请等待完成后停用');if(id==='builtin.cover-local'&&!enabled){for(const handle of media.sources.keys())media.closeSource(handle)};const result=await plugins.set(id,enabled,config);media.autoEnabled=plugins.enabled('cover-local');await db.call('settings',{plugins:plugins.serialize()});changed();return result},
 async loadPlugin(){const settings=await db.call('settings');if(!settings.developerMode)throw Error('请先启用开发模式；本地插件按可信代码执行');const choice=await dialog.showOpenDialog(window!,{title:'选择可信本地插件目录',properties:['openDirectory']});if(choice.canceled||!choice.filePaths[0])return plugins.list();const folder=await fs.realpath(choice.filePaths[0]);const manifest=JSON.parse(await fs.readFile(path.join(folder,'manifest.json'),'utf8'));const entry=await fs.realpath(path.resolve(folder,manifest.hostEntry??'host.mjs'));if(!entry.startsWith(folder+path.sep))throw Error('插件入口越出选定目录');const module=await import(pathToFileURL(entry).href);if(typeof module.setup!=='function')throw Error('插件必须导出 setup');plugins.register({manifest,setup:module.setup});const result=await plugins.set(manifest.id,true,manifest.defaults??{});changed();return result},
 async settings(patch:Record<string,unknown>){const allowed=['theme','themePreset','accentColor','fit','cardWidth','developerMode','lastFolder','lastBrowse','views','cacheGB','indexConcurrency','coverConcurrency','coverQuality','scrapeEnabled','scrapeProviders','scrapeConcurrency','scrapeDownloadCover','scrapeAutoSetCover','actressSort','movieSort'];if(Object.keys(patch).some(k=>!allowed.includes(k)))throw Error('不支持的设置');if(patch.themePreset!==undefined&&!['custom','aurora','ocean','nebula','sunset','blossom','forest','graphite'].includes(String(patch.themePreset)))throw Error('无效的主题预设');if(patch.accentColor!==undefined&&patch.accentColor!==null&&(typeof patch.accentColor!=='string'||!/^#[0-9a-f]{6}$/i.test(patch.accentColor)))throw Error('无效主题颜色');if(patch.theme&&!['light','dark','system'].includes(String(patch.theme)))throw Error('无效主题');if(patch.cacheGB!==undefined&&(!Number.isFinite(patch.cacheGB)||Number(patch.cacheGB)<1||Number(patch.cacheGB)>100))throw Error('缓存上限必须在 1–100 GB 之间');for(const key of ['indexConcurrency','coverConcurrency'])if(patch[key]!==undefined&&(!Number.isInteger(patch[key])||Number(patch[key])<1||Number(patch[key])>16))throw Error('并发数必须是 1–16 的整数');if(patch.coverQuality!==undefined&&!coverQualities.some(item=>item.value===patch.coverQuality))throw Error('无效封面分辨率');for(const key of ['scrapeEnabled','scrapeDownloadCover','scrapeAutoSetCover'])if(patch[key]!==undefined&&typeof patch[key]!=='boolean')throw Error('刮削开关必须是布尔值');if(patch.scrapeConcurrency!==undefined&&(!Number.isInteger(patch.scrapeConcurrency)||Number(patch.scrapeConcurrency)<1||Number(patch.scrapeConcurrency)>8))throw Error('刮削并发数必须是 1–8 的整数');if(patch.scrapeProviders!==undefined){if(!Array.isArray(patch.scrapeProviders)||!patch.scrapeProviders.length||!patch.scrapeProviders.every((id:unknown)=>typeof id==='string'&&scrapeProviders.some(provider=>provider.id===id)))throw Error('刮削数据源配置无效')}if(patch.actressSort!==undefined&&!['work-desc','work-asc','name-asc','age-asc','age-desc','recent-desc'].includes(String(patch.actressSort)))throw Error('无效的演员排序方式');if(patch.movieSort!==undefined&&!['recent-desc','code-asc','release-desc','duration-desc','title-asc'].includes(String(patch.movieSort)))throw Error('无效的电影排序方式');await db.call('settings',patch);if(patch.coverQuality!==undefined){media.coverQuality=patch.coverQuality as CoverQuality;media.resetFailures();send('thumbnail-cache-cleared')}if(patch.indexConcurrency!==undefined)indexConcurrency=Number(patch.indexConcurrency);if(patch.coverConcurrency!==undefined){coverConcurrency=Number(patch.coverConcurrency);media.thumbnailConcurrency=coverConcurrency}if(patch.theme){nativeTheme.themeSource=patch.theme as 'light'|'dark'|'system';syncWindowTheme()}if(Object.keys(patch).some(key=>!['lastFolder','lastBrowse','views'].includes(key)))send('settings-changed')},
 async clearCache(){await media.clearCache();send('thumbnail-cache-cleared')},
 async pruneStorage(){const result=await media.pruneStorage();send('thumbnail-cache-cleared');return result},
 async exportLibrary(){const result=await dialog.showSaveDialog(window!,{title:'导出管理包（不含原媒体）',defaultPath:'我的媒体库.vmlibrary',filters:[{name:'VideoManager 管理包',extensions:['vmlibrary']}]});if(result.canceled||!result.filePath)return null;return exportArchive(db,dataDir,result.filePath,path.join(here,'database.cjs'))},
 async importLibrary(){const result=await dialog.showOpenDialog(window!,{title:'导入为独立媒体库',properties:['openFile'],filters:[{name:'VideoManager 管理包',extensions:['vmlibrary']}]});if(result.canceled||!result.filePaths[0])return null;const id=randomUUID();const dest=path.join(userData,'libraries',id);const {records,manifest}=await inspectArchive(result.filePaths[0],dest);const existing=catalog.libraries.find(l=>l.id===manifest.libraryId||l.originId===manifest.libraryId);if(existing){const answer=await dialog.showMessageBox(window!,{type:'question',title:'此媒体库已存在',message:'已存在对应的媒体库：'+existing.name,detail:'可以打开现有媒体库，或创建独立副本。现有数据不会被覆盖。',buttons:['打开现有媒体库','创建独立副本','取消'],defaultId:0,cancelId:2});if(answer.response===2)return null;if(answer.response===0){await common.switchLibrary(existing.id);return existing.id}}const imported=new WorkerClient(path.join(here,'database.cjs'),'导入');try{await imported.call('init',path.join(dest,'library.sqlite'),false);await imported.call('importRecords',records);catalog.libraries.push({id,originId:manifest.libraryId,name:'导入的媒体库 '+new Date().toLocaleDateString('zh-CN')});await writeCatalog();changed();return id}finally{imported.close()}},
 async switchLibrary(id:string){if(!catalog.libraries.some(l=>l.id===id))throw Error('媒体库不存在');if(operations.busy)throw Error('请等待文件操作完成');await disposeLibrary();catalog.current=id;await writeCatalog();await initLibrary(id);send('library-switched');changed()},
 async diagnostics(){const result=await dialog.showSaveDialog(window!,{title:'导出诊断（隐藏媒体完整路径）',defaultPath:'VideoManager-diagnostics.json'});if(result.canceled||!result.filePath)return null;const redact=(text:string)=>text.replace(/[A-Za-z]:[\\/][^\n"；]+/g,'[本地路径]');await fs.writeFile(result.filePath,JSON.stringify({version:app.getVersion(),versions:process.versions,platform:process.platform,plugins:plugins.list(),tasks:[...tasks.values()].map(t=>({...t,message:redact(t.message),results:t.results?.map(r=>({...r,source:'[本地路径]',destination:r.destination?'[本地路径]':null,message:redact(r.message)}))}))},null,2));return result.filePath},
 async scrapeProviders(){return scrape.providersInfo()},
 async scrapeStats(){return scrape.stats()},
 async scrapePreview(id:string){return scrape.preview(id)},
 async scrapeSearch(id:string,provider:string){return scrape.searchOne(id,provider)},
 async scrapeApply(id:string,provider:string){const meta=await scrape.apply(id,provider);send('entry-changed',await db.call<Entry>('entry',id));return meta},
 async scrapeMeta(id:string){return scrape.meta(id)},
 async scrapeSetCover(id:string){const entry=await scrape.setCover(id);send('entry-changed',entry);return entry},
 async scrapeClear(id:string){await scrape.clear(id)},
 async scrapeRun(selection:Selection){return scrape.run(selection)},
 async actresses(sort:'work-desc'|'work-asc'|'name-asc'|'age-asc'|'age-desc'|'recent-desc',offset:number,limit:number){return reader.call('actressList',sort,offset,limit)},
 async actressEnrich(){return scrape.enrichActresses()},
 async actressUpdate(id:string,data:Record<string,unknown>){await db.call('actressUpdate',id,data);changed()},
 async actressCoverOptions(id:string){return reader.call('actressCoverOptions',id,60)},
 async actressSetCover(id:string,entryId:string){await db.call('actressSetCover',id,entryId);changed()},
 async javMovies(sort:'recent-desc'|'code-asc'|'release-desc'|'duration-desc'|'title-asc',offset:number,limit:number){return reader.call('javMovieList',sort,offset,limit)}
}
function installIPC(){for(const [method,schema]of Object.entries(ipcSchemas)){ipcMain.handle('vm:'+method,async(event,...args)=>{const requestId=randomUUID();try{const sender=event.senderFrame;if(!window||event.sender!==window.webContents||sender!==window.webContents.mainFrame)throw Error('不允许的调用来源');const url=new URL(sender.url);if(!(url.protocol==='app:'&&url.hostname==='shell')&&!(process.env.ELECTRON_RENDERER_URL&&sender.url.startsWith(process.env.ELECTRON_RENDERER_URL)))throw Error('不允许的页面');if(JSON.stringify(args).length>1024*1024)throw Error('请求过大');const validated=schema.parse(args);const result=await (common[method as keyof typeof common] as (...a:any[])=>unknown)(...validated);return {ok:true,requestId,data:result}}catch(error){const message=error instanceof Error?error.message:String(error);logFailure(dataDir,{requestId,method,message});return {ok:false,requestId,error:{message,code:message.match(/^[A-Z_]+/)?.[0]??'OPERATION_FAILED'}}}})}}
async function protocols(){const ses=session.defaultSession;const trustedRenderer=(candidate:string)=>{try{const url=new URL(candidate);return (url.protocol==='app:'&&url.hostname==='shell')||!!(process.env.ELECTRON_RENDERER_URL&&candidate.startsWith(process.env.ELECTRON_RENDERER_URL))}catch{return false}};ses.setPermissionRequestHandler((wc,permission,callback,details)=>callback(permission==='fullscreen'&&wc===window?.webContents&&trustedRenderer(details.requestingUrl||wc.getURL())));ses.setPermissionCheckHandler((wc,permission,origin)=>permission==='fullscreen'&&wc===window?.webContents&&trustedRenderer(origin||wc.getURL()))
 await ses.protocol.handle('app',async request=>{const url=new URL(request.url);if(url.hostname!=='shell')return new Response('Not found',{status:404});const name=decodeURIComponent(url.pathname);const base=path.resolve(here,'../renderer');const file=path.resolve(base,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(base+path.sep))return new Response('Forbidden',{status:403});try{const bytes=await fs.readFile(file);const ext=path.extname(file);const mime=({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.woff2':'font/woff2','.png':'image/png'} as Record<string,string>)[ext]??'application/octet-stream';return new Response(bytes,{headers:{'Content-Type':mime,'X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' media: data:; media-src media:; connect-src 'self' media:; font-src 'self'; object-src 'none'; frame-src 'none'; base-uri 'none'"}})}catch{return new Response('Not found',{status:404})}})
 await ses.protocol.handle('media',async request=>{let handle:fs.FileHandle|undefined;try{const url=new URL(request.url);if(url.hostname!=='resource'||!['GET','HEAD'].includes(request.method))return new Response(null,{status:405});const lease=media.resolve(url.pathname.slice(1));handle=await fs.open(lease.path,'r');const stat=await handle.stat({bigint:true});if(lease.identity){const parts=lease.identity.split(':');if(stat.ino.toString()!==parts[1]||stat.dev.toString()!==parts[0])throw Error('SOURCE_CHANGED')};const size=Number(stat.size);const range=parseRange(request.headers.get('range'),size);const headers:Record<string,string>={'Content-Type':lease.mime,'Accept-Ranges':'bytes','X-Content-Type-Options':'nosniff','Access-Control-Allow-Origin':'app://shell','Cache-Control':'private, max-age=3600'};if(!range){await handle.close();return new Response(null,{status:416,headers:{...headers,'Content-Range':`bytes */${size}`}})}headers['Content-Length']=String(range.end-range.start+1);if(range.partial)headers['Content-Range']=`bytes ${range.start}-${range.end}/${size}`;if(request.method==='HEAD'||size===0){await handle.close();return new Response(null,{status:range.partial?206:200,headers})}const stream=handle.createReadStream({start:range.start,end:range.end,autoClose:true});request.signal.addEventListener('abort',()=>stream.destroy(),{once:true});return new Response(Readable.toWeb(stream) as ReadableStream,{status:range.partial?206:200,headers})}catch{await handle?.close().catch(()=>{});return new Response('资源不可用',{status:404})}})
}
async function createWindow(){window=new BrowserWindow({width:1440,height:940,minWidth:1000,minHeight:650,show:false,title:'VideoManager',backgroundColor:nativeTheme.shouldUseDarkColors?'#0f141a':'#f4f7f9',titleBarStyle:'hidden',titleBarOverlay:{color:nativeTheme.shouldUseDarkColors?'#0f141a':'#f4f7f9',symbolColor:nativeTheme.shouldUseDarkColors?'#f1f5f9':'#152231',height:40},webPreferences:{preload:path.join(here,'../preload/index.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true}});window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',(event,url)=>{if(url!==window?.webContents.getURL())event.preventDefault()});window.on('ready-to-show',()=>{if(process.env.VM_TEST_HIDDEN!=='1')window?.show()});window.on('close',event=>{if(!closing&&sharing?.keepInTray){event.preventDefault();ensureTray();window?.hide();return}if(operations?.busy&&!closing){event.preventDefault();void dialog.showMessageBox(window!,{type:'info',message:'文件操作正在执行，请等待任务完成或先在后台任务中取消。'})}});window.on('closed',()=>{window=null});if(process.env.ELECTRON_RENDERER_URL)await window.loadURL(process.env.ELECTRON_RENDERER_URL);else await window.loadURL('app://shell/index.html')}
app.on('second-instance',()=>{window?.show();window?.focus()});app.on('window-all-closed',()=>app.quit());app.on('before-quit',event=>{if(!closing){event.preventDefault();closing=true;void Promise.allSettled([sharing?.stop(),mpv?.dispose()]).finally(()=>app.quit());return}sharing?.dispose();tray?.destroy();media?.close();nativeFs?.close();indexer?.kill();db?.close();reader?.close();images?.close()})
if(single)void app.whenReady().then(async()=>{await fs.mkdir(userData,{recursive:true});try{catalog=JSON.parse(await fs.readFile(path.join(userData,'catalog.json'),'utf8'))}catch{const id=randomUUID();catalog={current:id,libraries:[{id,name:'我的媒体库'}]};await writeCatalog()}await initLibrary(catalog.current);await protocols();installIPC();await createWindow();const interval=setInterval(()=>{void db.call('settings').then(settings=>media.trimCache(Number(settings.cacheGB??5)*1024**3)).catch(error=>logFailure(dataDir,{method:'cache',message:String(error)}))},15*60*1000);interval.unref();if(!app.isPackaged&&process.env.VM_TEST_ROOT){const grant=randomUUID();grants.set(grant,{path:path.resolve(process.env.VM_TEST_ROOT)});await common.addRoot(grant)}}).catch(async error=>{console.error(error);await dialog.showMessageBox({type:'error',title:'VideoManager 启动失败',message:String(error)});app.quit()})
