import {coverWidth,thumbnailName,defaultCoverQuality,type CoverQuality} from '../../../../packages/contracts/covers'
import { dialog } from 'electron'
import fs from 'node:fs/promises'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import { NativeClient } from '../../../../packages/platform/native'
import { discoverKind } from '../../../../packages/domain'
import type { Crop,Entry,Frame,CoverSource } from '../../../../packages/contracts'
import type { WorkerClient } from './worker'

type Lease={path:string;entryId:string|null;revision:number;identity:string|null;expires:number;mime:string}
type Source={path:string;entry:Entry|null;kind:string;name:string;decoder:NativeClient|null;duration:number;generation:number;identity:string}
type Snapshot={path:string;sourceId:string|null;sourceRevision:number;identity:string|null;pts:string;generation:number;handle:string|null;expires:number;independent?:boolean;readyCover?:boolean}
const hamming=(left:string,right:string)=>{let distance=Math.abs(left.length-right.length);for(let index=0;index<Math.min(left.length,right.length);index++)if(left[index]!==right[index])distance++;return distance}
export class MediaService {
 leases=new Map<string,Lease>();sources=new Map<string,Source>();frames=new Map<string,Snapshot>()
 private thumbs=new Map<string,Promise<string>>();private queue:Promise<unknown>=Promise.resolve();private cacheClear:Promise<void>|null=null;private errors=new Map<string,{at:number;message:string}>();private thumbActive=0;private thumbWaiting:{priority:boolean;start:()=>void}[]=[]
 private probing=new Set<string>();private closed=false;private paused=false;private recommendationRound=new Map<string,number>();private recommendations=new Map<string,string[]>();autoEnabled=true;coverQuality:CoverQuality=defaultCoverQuality;private thumbLimit=2
 get thumbnailConcurrency(){return this.thumbLimit}
 set thumbnailConcurrency(value:number){this.thumbLimit=value;this.drainThumbnails()}
 private drainThumbnails(){while(this.thumbActive<this.thumbLimit&&this.thumbWaiting.length)this.thumbWaiting.shift()!.start()}
 constructor(public dataDir:string,public nativeDir:string,public db:WorkerClient,public images:WorkerClient,public nativeFs:NativeClient,public broadcast:()=>void){}
 async sourcePath(e:Entry){const root=await this.db.call('root',e.rootId);if(!root.path||['offline','mismatch'].includes(root.state))throw Error('资源目录离线，请连接磁盘后重试');const full=path.resolve(root.path,...e.rel.split('/'));const rel=path.relative(root.path,full);if(rel.startsWith('..')||path.isAbsolute(rel))throw Error('资源路径越界');const stat=await this.nativeFs.call('stat',{path:full});if(stat.identity!==e.identity||stat.reparse)throw Error('SOURCE_CHANGED：原文件已被替换，请刷新目录');return full}
 grant(file:string,mime:string,entry:Entry|null=null){const token=randomUUID();this.leases.set(token,{path:file,mime,entryId:entry?.id??null,revision:entry?.revision??0,identity:entry?.identity??null,expires:Date.now()+12*60*60*1000});return `media://resource/${token}`}
 resolve(token:string){const lease=this.leases.get(token);if(!lease||lease.expires<Date.now())throw Error('媒体访问已过期');return lease}
 release(url:string){try{this.leases.delete(new URL(url).pathname.slice(1))}catch{}}
 resetFailures(){this.errors.clear();for(const [key,frame]of this.frames)if(frame.expires<Date.now())this.deleteFrame(key);for(const [key,lease]of this.leases)if(lease.expires<Date.now())this.leases.delete(key)}
 private serialize<T>(fn:()=>Promise<T>):Promise<T>{const promise=this.queue.then(fn,fn);this.queue=promise.catch(()=>{});return promise}
 private withThumbnailSlot<T>(fn:()=>Promise<T>,priority:boolean){return new Promise<T>((resolve,reject)=>{const start=()=>{this.thumbActive++;void fn().then(resolve,reject).finally(()=>{this.thumbActive--;this.drainThumbnails()})};if(this.thumbActive<this.thumbnailConcurrency)start();else{const pending={priority,start};if(priority){const index=this.thumbWaiting.findIndex(item=>!item.priority);this.thumbWaiting.splice(index<0?this.thumbWaiting.length:index,0,pending)}else this.thumbWaiting.push(pending)}})}
 private isTemporary(file:string){const base=path.resolve(this.dataDir,'temp')+path.sep;return path.resolve(file).startsWith(base)}
 private deleteFrame(token:string){const frame=this.frames.get(token);if(!frame)return;this.frames.delete(token);const shared=[...this.frames.values()].some(item=>item.path===frame.path);if(!shared){for(const [lease,url]of this.leases)if(url.path===frame.path)this.leases.delete(lease);if(this.isTemporary(frame.path))void fs.unlink(frame.path).catch(()=>{})}}
 private clearRecommendation(target:string){for(const token of this.recommendations.get(target)??[])this.deleteFrame(token);this.recommendations.delete(target)}
 async scheduleProbe(rootId:string){if(this.probing.has(rootId)||this.closed)return;this.probing.add(rootId);let changed=false;try{while(!this.closed){if(this.paused){await new Promise(resolve=>setTimeout(resolve,150));continue}const rows=await this.db.call<Entry[]>('unprobed',rootId,50);if(!rows.length)break;for(const e of rows){if(this.closed)return;await this.serialize(async()=>{if(this.closed||this.paused)return;try{if(!e.size)throw Error('空文件无法解码');const file=await this.sourcePath(e);let info:any;if(e.kind==='image'&&e.ext!=='bmp')info=await this.images.call('probe',file);else{const decoder=new NativeClient(path.join(this.nativeDir,'vm-media.exe'));try{info=await decoder.call('open',{path:file})}finally{decoder.close()}}await this.db.call('metadata',e.id,e.revision,info);changed=true}catch(error){if(this.closed)return;await this.db.call('metadata',e.id,e.revision,{error:String(error)});changed=true}})}await new Promise(resolve=>setTimeout(resolve,40))}}catch{/* Process shutdown interrupts background probes. */}finally{this.probing.delete(rootId);if(changed&&!this.closed)this.broadcast()}}
 async pauseWork(){this.paused=true;await this.queue;this.releaseAll()}
 resumeWork(){this.paused=false;this.resetFailures()}
 async media(id:string,purpose:string){const e=await this.db.call<Entry>('entry',id);if(purpose==='original'){const full=await this.sourcePath(e);const mime=e.kind==='image'?({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',bmp:'image/bmp'}[e.ext]??'application/octet-stream'):e.ext==='webm'?'video/webm':e.ext==='mov'?'video/quicktime':e.ext==='mkv'?'video/x-matroska':'video/mp4';return this.grant(full,mime,e)}
  if(this.cacheClear)await this.cacheClear
  const key=`${id}-${e.revision}-${e.coverRevision}-${this.coverQuality}`;const error=this.errors.get(key);if(error&&Date.now()-error.at<60000)throw Error(error.message)
  let pending=this.thumbs.get(key);if(!pending){pending=this.withThumbnailSlot(()=>this.thumbnail(e),true);this.thumbs.set(key,pending);void pending.catch(err=>this.errors.set(key,{at:Date.now(),message:String(err)})).finally(()=>this.thumbs.delete(key))}
  return this.grant(await pending,'image/webp')
 }
 async thumbnail(e:Entry){
  if(this.closed||this.paused)throw Error('文件操作期间预览暂时停止')
  const cache=path.join(this.dataDir,'cache');await fs.mkdir(cache,{recursive:true});let target=path.join(cache,thumbnailName(e,e.coverMode==='manual'?e.coverQuality:this.coverQuality));try{await fs.access(target);return target}catch{}
  if(['offline','mismatch'].includes(e.rootState)){const legacy=path.join(cache,`thumb-${e.id}-${e.revision}-${e.coverRevision}.webp`);try{await fs.access(legacy);return legacy}catch{}}
  if(e.coverMode==='auto'&&e.coverHash&&coverWidth(e.coverQuality)!==coverWidth(this.coverQuality)&&!['offline','mismatch'].includes(e.rootState)){await this.generateAutomatic(e);e=await this.db.call<Entry>('entry',e.id)}
  let source:string
  if(e.coverHash){source=path.join(this.dataDir,e.coverMode==='manual'?'objects':'cache',e.coverHash+'.png');try{await fs.access(source)}catch{if(e.coverMode==='manual')throw Error('手动封面对象缺失');source=await this.generateAutomatic(e)}}
  else if(e.kind==='image'){source=await this.sourcePath(e);if(e.ext==='bmp')source=(await this.decodeTemporary(e,0)).path;else{const metadata=await this.images.call('probe',source);await this.db.call('metadata',e.id,e.revision,metadata)}}
  else source=await this.generateAutomatic(e)
  e=await this.db.call<Entry>('entry',e.id);if(e.coverHash)source=path.join(this.dataDir,e.coverMode==='manual'?'objects':'cache',e.coverHash+'.png');target=path.join(cache,thumbnailName(e,e.coverMode==='manual'?e.coverQuality:this.coverQuality));await this.images.call('thumbnailTo',source,target,coverWidth(e.coverMode==='manual'?e.coverQuality:this.coverQuality));return target
 }
 async indexThumbnail(e:Entry){if(this.cacheClear)await this.cacheClear;if(this.closed||this.paused||e.kind==='folder'&&e.subtree===0)return;const key=`${e.id}-${e.revision}-${e.coverRevision}-${this.coverQuality}`;let pending=this.thumbs.get(key);if(!pending){pending=this.withThumbnailSlot(()=>this.thumbnail(e),false);this.thumbs.set(key,pending);void pending.then(()=>this.thumbs.delete(key),()=>this.thumbs.delete(key))}await pending}
 async decodeTemporaryBatch(e:Entry,times:number[]|((duration:number)=>number[])){const decoder=new NativeClient(path.join(this.nativeDir,'vm-media.exe'));const frames:any[]=[];try{const full=await this.sourcePath(e);const meta=await decoder.call('open',{path:full});await this.db.call('metadata',e.id,e.revision,meta);const directory=path.join(this.dataDir,'temp');await fs.mkdir(directory,{recursive:true});const requested=typeof times==='function'?times(Number(meta.duration??0)):times;for(const time of requested){const output=path.join(directory,randomUUID()+'.png');try{const frame=await decoder.call('frame',{time,step:0,output},20000);const normalized=await this.images.call('normalize',output,directory,frame.rotation);frames.push({...normalized,...frame,sourceId:e.id,sourceRevision:e.revision,identity:e.identity})}catch(error){if(requested.length===1)throw error}finally{await fs.unlink(output).catch(()=>{})}}if(!frames.length)throw Error('视频不能解码');return frames}finally{decoder.close()}}
 async decodeTemporary(e:Entry,time:number){return (await this.decodeTemporaryBatch(e,[time]))[0]!}
 async generateAutomatic(e:Entry){if(!this.autoEnabled)throw Error('自动封面插件已停用');const frames=await this.recommendInternal(e,0,1);const first=frames[0];if(!first)throw Error(e.kind==='folder'?'此目录暂无可用封面':'视频不能解码，请指定图片封面');try{const snapshot=this.frames.get(first.token)!;const crop={mode:'cover',x:.5,y:.5,zoom:1};const result=snapshot.readyCover?{hash:path.basename(snapshot.path,'.png'),path:path.join(this.dataDir,'cache',path.basename(snapshot.path))}:await this.images.call('crop',snapshot.path,path.join(this.dataDir,'cache'),crop,coverWidth(this.coverQuality));if(snapshot.readyCover&&snapshot.path!==result.path)await fs.copyFile(snapshot.path,result.path);if(this.autoEnabled)await this.db.call('cover',e.id,e.coverRevision,{mode:'auto',hash:result.hash,source:snapshot.sourceId,pts:snapshot.pts,crop,quality:this.coverQuality},true);return result.path}finally{for(const frame of frames)this.deleteFrame(frame.token)}}
 async source(id:string|null):Promise<CoverSource|null>{let entry:Entry|null=null;let file:string;let kind:string
  if(id){entry=await this.db.call('entry',id);if(!entry||entry.kind==='folder')throw Error('请选择图片或视频');file=await this.sourcePath(entry);kind=entry.kind}
  else {const choice=await dialog.showOpenDialog({title:'选择封面来源',properties:['openFile'],filters:[{name:'图片与视频',extensions:['jpg','jpeg','png','webp','gif','bmp','mp4','webm','mov','mkv','avi']}]});if(choice.canceled||!choice.filePaths[0])return null;file=choice.filePaths[0];kind=discoverKind(file)??'';if(!kind)throw Error('不支持此来源格式')}
  for(const handle of this.sources.keys())this.closeSource(handle)
  const stat=await this.nativeFs.call('stat',{path:file});if(stat.reparse)throw Error('请选择实际媒体文件，不能使用链接');const handle=randomUUID();let duration=0;let decoder:NativeClient|null=null
  if(kind==='video'||file.toLowerCase().endsWith('.bmp')){decoder=new NativeClient(path.join(this.nativeDir,'vm-media.exe'));try{const meta=await decoder.call('open',{path:file});duration=meta.duration;if(entry)await this.db.call('metadata',entry.id,entry.revision,meta)}catch(error){decoder.close();throw error}}
  this.sources.set(handle,{path:file,entry,kind,name:path.basename(file),decoder,duration,generation:0,identity:stat.identity});return {handle,name:path.basename(file),kind:kind as 'image'|'video',duration,sourceId:entry?.id??null,playbackUrl:kind==='video'?this.grant(file,file.toLowerCase().endsWith('.webm')?'video/webm':'video/mp4',entry):null}
 }
 async coverSnapshot(id:string){const e=await this.db.call<Entry>('entry',id);if(e.coverMode!=='manual'||!e.coverOriginal)throw Error('没有已保存的手动快照');const file=path.join(this.dataDir,'objects',e.coverOriginal+'.png');const info=await this.images.call('probe',file);let status='独立封面快照';if(e.coverSource){try{const source=await this.db.call<Entry>('entry',e.coverSource);if(source.state!=='present'||['offline','mismatch'].includes(source.rootState))status+=' · 来源已不可用';else if(e.kind==='folder'&&!(await this.db.call<Entry[]>('ancestors',source.id)).some(a=>a.id===e.id))status+=' · 来源不在此目录'}catch{status+=' · 来源已不可用'}}const token=randomUUID();this.frames.set(token,{path:file,sourceId:e.coverSource,sourceRevision:0,identity:null,pts:e.coverPts??'0',generation:0,handle:null,expires:Date.now()+3600000,independent:true});return {frame:{token,url:this.grant(file,'image/png'),time:0,pts:e.coverPts??'0',ordinal:0,width:info.width,height:info.height,duration:0,generation:0},status}}
 async frame(handle:string,time:number,step:number,generation:number):Promise<Frame>{const source=this.sources.get(handle);if(!source)throw Error('选帧会话已结束');source.generation=Math.max(source.generation,generation);const directory=path.join(this.dataDir,'temp');await fs.mkdir(directory,{recursive:true});let snapshot:any,info:any={time:0,pts:'0',ordinal:0,duration:source.duration}
  if(source.decoder){const output=path.join(directory,randomUUID()+'.png');info=await source.decoder.call('frame',{time,step,output},20000);snapshot=await this.images.call('normalize',output,directory,info.rotation);await fs.unlink(output).catch(()=>{})}
  else snapshot=await this.images.call('normalize',source.path,directory)
  if(source.generation!==generation)throw Error('FRAME_SUPERSEDED')
  const token=randomUUID();this.frames.set(token,{path:snapshot.path,sourceId:source.entry?.id??null,sourceRevision:source.entry?.revision??0,identity:source.identity,pts:info.pts,generation,handle,expires:Date.now()+3600000})
  return {token,url:this.grant(snapshot.path,'image/png'),time:info.time,pts:info.pts,ordinal:info.ordinal,width:snapshot.width,height:snapshot.height,duration:source.duration,generation}
 }
 closeSource(handle:string){this.sources.get(handle)?.decoder?.close();this.sources.delete(handle);for(const [token,frame]of this.frames)if(frame.handle===handle)this.deleteFrame(token)}
 async save(target:string,token:string,crop:Crop,revision:number,quality:'compact'|'original'|'high'|'balanced'|'fast'){const selected=this.frames.get(token);if(!selected||selected.expires<Date.now())throw Error('FRAME_NOT_READY：画面已过期，请重新选择');if(selected.sourceId&&!selected.independent){const source=await this.db.call<Entry>('entry',selected.sourceId);if(source.revision!==selected.sourceRevision)throw Error('来源已变化，请重新选择画面')}if(selected.handle){const source=this.sources.get(selected.handle);if(!source||source.generation!==selected.generation)throw Error('FRAME_NOT_READY：请等待最新画面');const stat=await this.nativeFs.call('stat',{path:source.path});if(stat.identity!==selected.identity)throw Error('来源已变化，请重新打开')}
  const objectDir=path.join(this.dataDir,'objects');const original=await this.images.call('normalize',selected.path,objectDir);const width=coverWidth(quality);const result=await this.images.call('crop',original.path,objectDir,crop,width)
  await this.db.call('cover',target,revision,{mode:'manual',hash:result.hash,original:original.hash,source:selected.sourceId,pts:selected.pts,crop,quality});this.clearRecommendation(target)
 }
 async recommend(target:string){const e=await this.db.call<Entry>('entry',target);this.clearRecommendation(target);const round=(this.recommendationRound.get(target)??-1)+1;this.recommendationRound.set(target,round);const frames=await this.serialize(()=>this.recommendInternal(e,round,6));this.recommendations.set(target,frames.map(frame=>frame.token));return frames}
 private async recommendInternal(e:Entry,round:number,limit:number):Promise<Frame[]>{let all=await this.db.call<Entry[]>(limit===1?'automaticCandidates':'candidates',e.id);if(limit===1&&e.kind==='folder'&&all.every(item=>item.kind==='folder'&&coverWidth(item.coverQuality)!==coverWidth(this.coverQuality)))all=await this.db.call<Entry[]>('candidates',e.id);const start=Date.now();const scored:{frame:Frame;score:number;fingerprint:string;sourceId:string}[]=[]
  const distributed=(items:Entry[],limit:number)=>items.length<=limit?items:Array.from({length:limit},(_,i)=>items[Math.floor(i*(items.length-1)/(limit-1))]!)
  const candidates=limit===1?all:[...distributed(all.filter(v=>v.kind==='image'),24),...distributed(all.filter(v=>v.kind==='video'),4)]
  for(const candidate of candidates){if(Date.now()-start>10000)break;try{let frames:any[]=[]
   if(limit===1&&candidate.coverHash&&(candidate.coverMode==='manual'||coverWidth(candidate.coverQuality)===coverWidth(this.coverQuality))){const saved=path.join(this.dataDir,candidate.coverMode==='manual'?'objects':'cache',candidate.coverHash+'.png');try{const metadata=await this.images.call('probe',saved);const token=randomUUID();this.frames.set(token,{path:saved,sourceId:candidate.id,sourceRevision:candidate.revision,identity:candidate.identity,pts:candidate.coverPts??'0',generation:0,handle:null,expires:Date.now()+3600000,readyCover:true});return [{token,url:this.grant(saved,'image/png'),time:0,pts:candidate.coverPts??'0',ordinal:0,width:metadata.width,height:metadata.height,duration:0,generation:0}]}catch{}}
   if(candidate.kind==='folder')continue
   if(candidate.coverHash&&candidate.kind!=='video'){const saved=path.join(this.dataDir,candidate.coverMode==='manual'?'objects':'cache',candidate.coverHash+'.png');try{const metadata=await this.images.call('probe',saved);frames.push({path:saved,width:metadata.width,height:metadata.height,time:Number(candidate.coverPts??0),pts:candidate.coverPts??'0',ordinal:0,duration:candidate.duration??0,preferred:candidate.coverMode==='manual'})}catch{}}
   if(candidate.kind==='image'&&candidate.ext!=='bmp'){const source=await this.sourcePath(candidate);const normalized=limit===1?{path:source,...await this.images.call('probe',source)}:await this.images.call('normalize',source,path.join(this.dataDir,'temp'));frames=[{...normalized,time:0,pts:'0',ordinal:0,duration:0}]}
   else {const sampleCount=limit===1?3:12;const shift=limit===1?0:((round%5)-2)*.012;const startFactor=limit===1?0.1:0.06;const span=limit===1?0.8:0.88;frames.push(...await this.decodeTemporaryBatch(candidate,duration=>duration>0?Array.from({length:sampleCount},(_,index)=>duration*Math.max(.025,Math.min(.975,startFactor+index*span/(sampleCount-1)+shift))):[0]))}
   for(const f of frames){if(scored.some(s=>s.sourceId===candidate.id&&s.frame.pts===f.pts)){if(this.isTemporary(f.path)&&!scored.some(s=>this.frames.get(s.frame.token)?.path===f.path))await fs.unlink(f.path).catch(()=>{});continue}const quality=await this.images.call('score',f.path);const token=randomUUID();this.frames.set(token,{path:f.path,sourceId:candidate.id,sourceRevision:candidate.revision,identity:candidate.identity,pts:f.pts,generation:0,handle:null,expires:Date.now()+3600000});scored.push({frame:{token,url:this.grant(f.path,'image/png'),time:f.time,pts:f.pts,ordinal:f.ordinal,width:f.width,height:f.height,duration:f.duration,generation:0},fingerprint:quality.fingerprint,score:quality.score+(f.preferred?1:0),sourceId:candidate.id})}
   if(limit===1&&scored.length)break
  }catch{/* Individual corrupt media does not abort the folder. */}}
  const ordered=scored.sort((a,b)=>b.score-a.score);const selected:typeof scored=[];const fill=(similarity:number,gapRatio:number)=>{for(const candidate of ordered){if(selected.length>=limit)break;if(selected.includes(candidate))continue;if(selected.some(item=>hamming(item.fingerprint,candidate.fingerprint)<=similarity))continue;const tooClose=selected.some(item=>item.sourceId===candidate.sourceId&&candidate.frame.duration>0&&Math.abs(item.frame.time-candidate.frame.time)<Math.max(.15,candidate.frame.duration*gapRatio));if(!tooClose)selected.push(candidate)}};for(const [similarity,gap]of [[4,.12],[3,.09],[2,.065],[0,.04]] as const)fill(similarity,gap);for(const discarded of ordered)if(!selected.includes(discarded))this.deleteFrame(discarded.frame.token);return selected.map(s=>s.frame)
 }
 async refreshAncestorCovers(target:string){const entry=await this.db.call<Entry>('entry',target);if(!entry.coverHash)return [];if(entry.coverMode==='manual')await fs.copyFile(path.join(this.dataDir,'objects',entry.coverHash+'.png'),path.join(this.dataDir,'cache',entry.coverHash+'.png'));return this.db.call<Entry[]>('refreshAncestorCovers',target,this.coverQuality)}
 async restore(target:string,revision:number){const e=await this.db.call<Entry>('entry',target);const candidates=await this.recommend(target);const first=candidates[0];if(!first)throw Error('未找到可用自动封面，原封面已保留');try{const snapshot=this.frames.get(first.token)!;const crop={mode:'cover',x:.5,y:.5,zoom:1};const result=await this.images.call('crop',snapshot.path,path.join(this.dataDir,'cache'),crop,coverWidth(this.coverQuality));await this.db.call('cover',e.id,revision,{mode:'auto',hash:result.hash,source:snapshot.sourceId,pts:snapshot.pts,crop,quality:this.coverQuality})}finally{this.clearRecommendation(target)}}
 async saveExternalCover(target:string,file:string,quality:CoverQuality=defaultCoverQuality):Promise<Entry>{const e=await this.db.call<Entry>('entry',target);if(e.kind!=='video'&&e.kind!=='image')throw Error('只能为媒体设置封面');const objectDir=path.join(this.dataDir,'objects');const original=await this.images.call('normalize',file,objectDir);const crop={mode:'cover',x:.5,y:.5,zoom:1};const result=await this.images.call('crop',original.path,objectDir,crop,coverWidth(quality));await this.db.call('cover',target,e.coverRevision,{mode:'manual',hash:result.hash,original:original.hash,source:null,pts:'0',crop,quality});this.clearRecommendation(target);return this.db.call<Entry>('entry',target)}
 clearCache(){
  if(this.cacheClear)return this.cacheClear
  // Existing writers finish first; new thumbnail requests wait for the same clear.
  this.cacheClear=(async()=>{
   await Promise.allSettled([...this.thumbs.values()]);await this.queue
   const dir=path.resolve(this.dataDir,'cache');if(path.dirname(dir)!==path.resolve(this.dataDir))throw Error('缓存路径无效')
   await fs.rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100});await fs.mkdir(dir,{recursive:true})
   this.errors.clear();this.broadcast()
  })().finally(()=>{this.cacheClear=null})
  return this.cacheClear
 }
 async trimCache(maxBytes=5*1024**3){const dir=path.join(this.dataDir,'cache');const files=await fs.readdir(dir).catch(()=>[]);const infos=await Promise.all(files.map(async name=>{const file=path.join(dir,name);const stat=await fs.stat(file);return {file,size:stat.size,time:stat.atimeMs}}));let size=infos.reduce((s,f)=>s+f.size,0);for(const info of infos.sort((a,b)=>a.time-b.time)){if(size<=maxBytes)break;if([...this.leases.values()].some(l=>l.path===info.file&&l.expires>Date.now()))continue;await fs.unlink(info.file).catch(()=>{});size-=info.size}}
 async cleanupStorage(){const temp=path.resolve(this.dataDir,'temp');if(path.dirname(temp)!==path.resolve(this.dataDir))throw Error('临时目录无效');await fs.rm(temp,{recursive:true,force:true});await fs.mkdir(temp,{recursive:true});return this.pruneStorage()}
 async pruneStorage(){await this.queue;const references=await this.db.call<{cache:string[];objects:string[]}>('storageReferences');let files=0,bytes=0;const active=new Set([...this.leases.values()].filter(item=>item.expires>Date.now()).map(item=>path.resolve(item.path)));const clean=async(directory:'cache'|'objects'|'temp',keep:Set<string>)=>{const dir=path.resolve(this.dataDir,directory);if(path.dirname(dir)!==path.resolve(this.dataDir))throw Error('存储路径无效');for(const name of await fs.readdir(dir).catch(()=>[])){const file=path.join(dir,name);const stat=await fs.stat(file).catch(()=>null);if(!stat?.isFile()||keep.has(name)||active.has(path.resolve(file)))continue;await fs.unlink(file).catch(()=>{});files++;bytes+=stat.size}};await clean('cache',new Set(references.cache));await clean('objects',new Set(references.objects));await clean('temp',new Set([...this.frames.values()].map(item=>path.basename(item.path))));this.errors.clear();return {files,bytes}}
 releaseAll(){for(const key of this.sources.keys())this.closeSource(key);this.leases.clear();for(const token of [...this.frames.keys()])this.deleteFrame(token);this.recommendations.clear()}
 close(){this.closed=true;this.releaseAll()}
}
